### ISSUE TITLE
add youtube icon to website header

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#101]
@necelentano - могли бы посмотреть? У нас небольшой видеоканал развивается - https://www.youtube.com/channel/UCrDKAbWze5ai38Qr5w124Ww

Там? где сейчас ссылка на гитхаб сверху на сайте, могли бы ссылку на youtube добавить?

**Comment by necelentano** [comment]
Добавил иконку YouTube с ссылкой на канал в header сайта.

**Comment by epogrebnyak** [comment]
@necelentano, здорово!  отдельным ишбю предлагаю посмотреть как завести иконки видео на первую страницу
