### ISSUE TITLE
добавить новость в блог на русскую версию сайта

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#102]
https://docs.google.com/document/d/1DrbaKAQX4CXckRPeEDA0j7KNc_kKDjyb/edit?usp=sharing&ouid=107614683558087440968&rtpof=true&sd=true

**Comment by epogrebnyak** [comment]
@AntonBoch1244, что можно поправить:

- [x] заголовок: "Учебный центр МФЦ провел гостевые лекции по финансовым рынкам"
- [x] заменить все типы кавычек на ", прогнать через npm run prettier
- [x] сократить слаг mfc-learning-centre-guest-lectures (на сайте про МГИМО все)
- [x] добавить ссылку на “Финансовая экономика и финансовые технологии” в начале и в конце статьи
- [x] АНО «ИДПО МФЦ» дать ссылку на https://www.educenter.ru/
- [x] на будущее - может быть на форке сделать Github pages и с него смотреть превью?

(надо было мне в PR написать, было бы правильнее)

**Comment by AntonBoch1244** [comment]
Было бы правильнее на мой взгляд не мержить, а дать комментарий к коду. GitHub позволяет это делать.

**Comment by epogrebnyak** [comment]
> Было бы правильнее на мой взгляд не мержить, а дать комментарий к коду. GitHub позволяет это делать.

Да, я об этом написал, но чтобы понять, что менять нужен превью - в идеале, если на форке у вас настроен Github Pages и можно посомтреть как статья выглядит, тогда понятно что менять надо.

**Comment by epogrebnyak** [comment]
@AntonBoch1244 - правило: кто ишью открыл, тот его и закрывает.

**Comment by epogrebnyak** [comment]
ошиблись с датой кстати - не 07, а 17, поправил
