### ISSUE TITLE
новости в блог про гостевые лекции Крупнова и Маракуевой [1h]

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#104]
Готовим в режиме `draft=True` (не публикутся на сайт), новости в блог:

- [x] https://mgimo.ru/about/news/announce/krupnov/
- [ ] https://mgimo.ru/about/news/announce/marakueva/

Нужно перенести текст новости в маркдауне на наш сайт, дать ссылку на исходную новость и картинку плаката.

(Далее - редакция текста новости, вывешиваем видео встреч)

**Comment by epogrebnyak** [comment]
@AntonBoch1244 - здесь нужен текст по выступлению Крупнова

**Comment by epogrebnyak** [comment]
- [ ] slag 2022-04-20-lecture-a-krupnov-future-of-insurance-and-insurtech/ не очень удачный: `-а-` повисает, давайте его уберем

Поправлю:
- [ ] лекция уже прошла, все в прошлом времени
- [ ] смысл анонса - завлечь узнать больше о программе, дать больше информации о видео  
- [ ] разбиваем на абзацы
- [ ] делаем интереснее читать (см Medeiros блог)

**Comment by epogrebnyak** [comment]
```
Больше информации о поступлении в магистратуру “Цифровые финансы” вы можете узнать [здесь](http://pk.odin.mgimo.ru/master/cf.html).
```

это используем в другом месте

**Comment by epogrebnyak** [comment]
Сломал front matter я:

```
Error: Error building site: "/home/runner/work/finec-mgimo.github.io/finec-mgimo.github.io/content/ru/blog/2022-04-20-lecture-a-krupnov-future-of-insurance-and-insurtech/index.md:2:1": failed to unmarshal YAML: yaml: mapping values are not allowed in this context
```

**Comment by epogrebnyak** [comment]
@AntonBoch1244: 
- [ ] нужен драфт записи в блоге на основе https://mgimo.ru/about/news/announce/marakueva/
- [ ] использовать draft: True
- [ ] использовать формат, аналогичный лекции Крупнова
- [ ] текст исходной записи передать из анонса в прошедшее время
- [ ] возможное улучшение - у нас сейчас никак не задействованы тайм коды из видео в анонсе, там много полезной информации

**Comment by AntonBoch1244** [comment]
Принято.
