### ISSUE TITLE
сделать отдельный файл для описания программы "Цифровые финансы" [1h]

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#108]
https://docs.google.com/document/d/1TP1QuBtDqFe6SooRWcyhELy7-wtmS54c/edit

- не публикуем
- предлагаю сделать _index2.md (если не рушит верстку, проверить)

**Comment by epogrebnyak** [comment]
Может затрагивать: https://github.com/finec-mgimo/finec-mgimo.github.io/issues/88 (вынести текст - ЕП)

**Comment by AntonBoch1244** [comment]
Пока никаких изменений не делаю по этому issue. Ожидаю решения по #88.

**Comment by epogrebnyak** [comment]
> Пока никаких изменений не делаю по этому issue. 

В этом ишью как раз нужно преобразовать документ из google docs, высокий  приоритет. Когда будет сделано этот ишью, можно сделать #88.
