### ISSUE TITLE
Добавить презентацию "Цифровые финансы"

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#115]
https://speakerdeck.com/epogrebnyak/maghistierskaia-proghramma-tsifrovyie-finansy-nabor-2022-ghoda-finek-mgimo

**Comment by epogrebnyak** [comment]
<iframe class="speakerdeck-iframe" frameborder="0" src="https://speakerdeck.com/player/65f2b9d5fc204490b1b6148ab84f456b" title="Цифровые финансы - магистерская программа Финэка МГИМО " allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" style="border: 0px; background: padding-box padding-box rgba(0, 0, 0, 0.1); margin: 0px; padding: 0px; border-radius: 6px; box-shadow: rgba(0, 0, 0, 0.2) 0px 5px 40px; width: 560px; height: 314px;" data-ratio="1.78343949044586"></iframe>

**Comment by epogrebnyak** [comment]
Вставить iframe выше на страницу описания магистратуры

**Comment by vandaipham** [comment]
Вставил iframe на станицу описания цифровых финансов
https://finec.mgimo.ru/program/masters/digital-finance/

**Comment by epogrebnyak** [comment]
Apparently resolved by https://github.com/finec-mgimo/finec-mgimo.github.io/pull/148/commits/d969db7664e7adac13fb934228ba987583e0038f
