### ISSUE TITLE
Фото выпускников 2022 в блоге

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#119]
@super16 - механизм для показывания фото в блоге (одним боксом)

**Comment by epogrebnyak** [comment]
Место для экспериментальной демонстрации фото: https://github.com/finec-mgimo/finec-mgimo.github.io/blob/main/content/ru/blog/2022-06-09-graduates-2022/index.md

**Comment by epogrebnyak** [comment]
Нужно разместить следующие фото:

https://drive.google.com/file/d/1cmtJ8R3G_aaQiOOva3q9nXhFj0x7Plk0/view?usp=sharing
https://drive.google.com/file/d/1dMmCR8vyzaQpPZkFddeuQUxwjRiv_IHl/view?usp=sharing

**Comment by epogrebnyak** [comment]
![image](https://user-images.githubusercontent.com/9265326/172830256-5165b0fb-74c2-467f-8705-ef372d2f3881.png)
![image](https://user-images.githubusercontent.com/9265326/172830294-13a2d00a-3e10-4bf9-9505-64a23542581b.png)
![image](https://user-images.githubusercontent.com/9265326/172830333-a13f1d2a-c5a7-4105-8e8c-1bca93465ae8.png)

**Comment by epogrebnyak** [comment]
https://drive.google.com/file/d/1UYrN5TGFt4o9_oUE1KsbSzbrRJHD3mPF/view?usp=sharing - кадрировать

**Comment by epogrebnyak** [comment]
Опыт внедрения на адресе https://finec.mgimo.ru/blog/graduates-2022/:

1. Здорово, что показывает, выглядит красиво 
2. Заметно виснет при первом просмотре - серый квадрат (качает JS откуда-то)
3. Нет влево-вправо куда кликнуть, можно не догадаться, что надо клавиши нажимать 
4. Белый текст теряется светлых фото
5. Длинный текст наверное лучше не писать - не ясно куда перенесет

attn @super16 (не для быстрого фикса, делимся информацией)

**Comment by super16** [comment]
Поправил карусель:

- заменил фото на оптимизированные, сейчас всё должно загружаться без зависаний при первом просмотре
- добавлены стрелки переключения фото
- текст к фото теперь ниже и виден
