### ISSUE TITLE
нам нужны dependabot-* бранчи?

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#12]
Если нет - просьба удалить (мне кажется что нет).

Что еще можно подчистить в репо, что не относится к сайту факульета?

**Comment by epogrebnyak** [comment]
Для обсуждения - что делать с PR от депендабота? )

**Comment by necelentano** [comment]
Вроде отключил dependabot. Но, как я понял, можно будет замерджить эти PR.

**Comment by epogrebnyak** [comment]
@necelentano - посмотри плс - более глобальный вопрос - #20
