### ISSUE TITLE
Транскрибировать видео (Туризм)

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#120]
https://www.youtube.com/watch?v=PcmU01hmhEw

**Comment by epogrebnyak** [comment]
нужен текст видео, созданный автомтически, потом передаем для транскрибирования руками (можно получить через youtube-dl)

**Comment by epogrebnyak** [comment]
@AntonBoch1244 - можете посмотреть?

**Comment by epogrebnyak** [comment]
https://superuser.com/questions/927523/how-to-download-only-subtitles-of-videos-using-youtube-dl

**Comment by epogrebnyak** [comment]
https://gist.github.com/glasslion/b2fcad16bc8a9630dbd7a945ab5ebf5e

**Comment by epogrebnyak** [comment]
@hel8er, если возьметесь - результат - гуггл докс, открытый для редактирования.

**Comment by hel8er** [comment]
> @hel8er, если возьметесь - результат - гуггл докс, открытый для редактирования.

Нужны "грязные" субтитры или отредактировать?

**Comment by hel8er** [comment]
Done
https://docs.google.com/document/d/1NoZlAZnoQfVl_jSJV4UNichARTqz-8rMxEehwclCI1M/edit?usp=sharing

**Comment by epogrebnyak** [comment]
> Done https://docs.google.com/document/d/1NoZlAZnoQfVl_jSJV4UNichARTqz-8rMxEehwclCI1M/edit?usp=sharing

@hel8er, спасибо, ищем кто сделает слитный текст (редактор), потмо нужно будет добавить в раздел про бак.программу туризм.

Могли бы код указать, который использовали для youtube-dl?
