### ISSUE TITLE
Добавить значок с Telegram слева от значка Youtube вверху первой страницы

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#128]
Ссылка на ТГ: https://t.me/finec_mgimo

**Comment by epogrebnyak** [comment]
У меня вопрос - значок телеграмма мы каким-то шрифтом можем в тексте использовать?

**Comment by super16** [comment]
Такого типа шрифты не встречал, и не думаю, что это правильное решение для строчного представления значков и иконок. В таких случаях, как мне кажется, лучше использовать макросы, встраивающие SVG-файлы
