### ISSUE TITLE
Улучшенная фотокарусель

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#131]
По результатам #119 - дорабатывам фотокарусель чтобы ее можно было исопльзовать на разных страницах сайта.

Одна их страниц - кандидатов: "Партнерства" (фото визитов к партнерам факультета)

**Comment by super16** [comment]
Добавил [PR](https://github.com/finec-mgimo/finec-mgimo.github.io/pull/135), где улучшил карусель, что теперь при использовании в разметке, нужно задать название data-файла в виде аргумента. Тем самым компонент можно использовать в разных местах, задавая им названия отдельных файлов. Также добавил документацию по использованию. В качестве документации для разработчиков предлагаю использовать Markdown-разметку, то есть смотреть документацию можно прямо в IDE или в интерфейсе Github, добавил также в README.md ссылку на страницу с описанием карусели

**Comment by epogrebnyak** [comment]
> В качестве документации для разработчиков предлагаю использовать Markdown-разметку, то есть смотреть документацию можно прямо в IDE или в интерфейсе Github, 

По формату понятно - по месту - в README пока доку собираем?

**Comment by epogrebnyak** [comment]
> > В качестве документации для разработчиков предлагаю использовать Markdown-разметку, то есть смотреть документацию можно прямо в IDE или в интерфейсе Github,
> 
> По формату понятно - по месту - в README пока доку собираем?

кажется понял - в папке docs, хороший вариант.

**Comment by super16** [comment]
Можно ещё для полной неперекрываемости имён назвать директорию `.docs` вместо `docs`, т.е. чтобы оставить место для finec.mgimo.ru/docs, если появится такая необходимость

**Comment by epogrebnyak** [comment]
> Можно ещё для полной неперекрываемости имён назвать директорию `.docs` вместо `docs`, т.е. чтобы оставить место для finec.mgimo.ru/docs, если появится такая необходимость

Теоретически да, но мы все равно основной сайт через Github Pages в ветке gh-pages показываем,так что docs не будет задействован, но идея полезная. Предлагаю оставить docs.

**Comment by epogrebnyak** [comment]
Нам в PR предлагаю переименовать в примере /data в другой каталог для картиноки можно мерджить (не хочется подталкивать к хранению картинок в data )

**Comment by epogrebnyak** [comment]
> Можно ещё для полной неперекрываемости имён назвать директорию `.docs` вместо `docs`, т.е. чтобы оставить место для finec.mgimo.ru/docs, если появится такая необходимость

finec.mgimo.ru/docs хорошая идея,я что-то не подумал, что на имя домена может выйти

**Comment by epogrebnyak** [comment]
Я смерджил и подправил коммитами выше, надеюсь это закрывает вопрос с каруселью. @super16 - просьба посмотреть shortcodes.md - если что-то не так, правьте в мастер. Если все ок - просьба вы нажмите закрыть ишью.
