### ISSUE TITLE
Использовать для фото закругление

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#132]
У нас здесь есть фото: https://finec.mgimo.ru/blog/maxim-about-cmf-risk-management-2022/

Предлагаем использовать фото как здесь: https://finec.mgimo.ru/blog/2021-itmb-graduates/ (крупный круг или овал)

**Comment by BekKhojiev** [comment]
Хочу попробовать нашёл имг 
p>img, img {
    max-width: 100%;
    height: auto;
    border-radius: 50%;
}

**Comment by epogrebnyak** [comment]
> Хочу попробовать нашёл имг p>img, img { max-width: 100%; height: auto; border-radius: 50%; }

@BekKhojiev Вы источник для https://finec.mgimo.ru/blog/2021-itmb-graduates/ нашли? Уточните как там сделано

**Comment by BekKhojiev** [comment]
Я нашёл изображения в  https://finec.mgimo.ru/blog/maxim-about-cmf-risk-management-2022/
которую надо сделать круглым

**Comment by hel8er** [comment]
Я так понимаю это дубль #136? Сделано #141 pr

**Comment by epogrebnyak** [comment]
> Я так понимаю это дубль #136? Сделано #141 pr

да, почему-то задублировалось
