### ISSUE TITLE
Создать новую карусель (корпоративные визиты)

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#137]
Описание- в коммите ниже

**Comment by epogrebnyak** [comment]
@hel8er - может быть посмотрите? До 1h

**Comment by hel8er** [comment]
собрал того компаний здесь
https://www.figma.com/file/vH5AkM36cv68hnXlx1By7g/mgimo_partners?node-id=0%3A1

**Comment by epogrebnyak** [comment]
@hel8er - знаю вы новый вариант сделали, хорошо бы какую-то ссылку здесь на результат

**Comment by epogrebnyak** [comment]
https://finec.mgimo.ru/about/partners/

**Comment by epogrebnyak** [comment]
Проблема с аспектом - у нас не очень ландшафтные показываются, но для эксперимента - неплохо

**Comment by epogrebnyak** [comment]
@hel8er - теперь нужно перенести картинки с внешних адресов в локальную папку (в блоге). Попробовать использовать формат webp, если он дает выигрыш в размере файла.

**Comment by epogrebnyak** [comment]
Хотя webp можно не переводить
