### ISSUE TITLE
Разместить новый материал в раздел: Факультет > интервью декана

### ISSUE THREAD

**Issue by hel8er** [necelentano/finec-mgimo-v2#155]
https://finec.mgimo.ru/about/interview/
---
старый текст закомментировать, добавить следующий:
https://docs.google.com/document/d/1RBJmodxlc4lGUOgp2MsR_orH7y3I1xlJfGYraW_hd7U/edit?usp=sharing

**Comment by epogrebnyak** [comment]
Будет также закрывать #109

**Comment by epogrebnyak** [comment]
Берём фото из блога про ЦМФ

**Comment by epogrebnyak** [comment]
Сюда пойдет вот это интервью: https://mgimo.ru/about/news/main/finec-2022/

**Comment by epogrebnyak** [comment]
Дождитесь, я напишу, что исправили ошибки на сайте и можно будет переносить. 

Старое интервью удаляем, даём новое

**Comment by epogrebnyak** [comment]
@hel8er - можно вносить интервью на наш сайт, лучше хотелось бы побыстрее

**Comment by epogrebnyak** [comment]
В конце абзаца про ИТМБ - `На программе также есть бюджетные места`.
