### ISSUE TITLE
Неправильная ссылка [0.2h]

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#161]
![изображение](https://user-images.githubusercontent.com/9265326/176431984-40e3d6ed-00cd-4d01-bc04-a8a345a1d32d.png)

**Comment by epogrebnyak** [comment]
https://finec.mgimo.ru/program/undergrad/tourism/

**Comment by Ks-Roman** [comment]
### [Туризм (ТиГ)](https://finec.mgimo.ru/program/undergrad/tourism/)
