### ISSUE TITLE
интервью Даниила на сайт

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#169]

**Comment by Danielrsnv** [comment]
https://docs.google.com/document/d/1WoWuXg6UdmD7QKPdyRos5oBVko_Zgprdk6SxBlaWFaU/edit (ЕП: ранний драфт, не используем)

**Comment by epogrebnyak** [comment]
https://docs.google.com/document/d/1tD2o0TsilctfZ-7RomWNY3TPBEI1JtCk12xx8NuKK7o/edit

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/178141338-7b0ea077-6e04-4d60-8671-83b21170beb7.png)

**Comment by epogrebnyak** [comment]
@hel8er - сможете вывесить в блог как будет готов текст? фото перевести в jpeg и уменьшить до приемлимых размеров
