### ISSUE TITLE
добавить расшифровки видео Милены и Никиты

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#178]
https://finec.mgimo.ru/about/students/

https://github.com/finec-mgimo/finec-mgimo.github.io/blob/main/content/ru/about/students.md

Closes #57

**Comment by epogrebnyak** [comment]
Дополнительно - отсортировать видео по году выпуска (полее поздние сверху, более ранние снизу (видео с Виолой - в самом низу).

**Comment by MariSh178** [comment]
Расшифровка интервью с Миленой
Здравствуйте! Меня зовут Панасюк Милена, я студентка МГИМО. Я очень отзывчивый, открытый, позитивный человек. Еще в 9-м классе я поехала сюда на день открытых дверей,​ и когда я вошла в ВУЗ, я влюбилась с первого взгляда и поэтому очень хотела сюда поступить. Специальность выбрала спонтанно, решила, что хочу заниматься экономикой, хочу понимать, как это все раюботает, откуда берутся деньги. Поэтому я сюда поступила. Я очень довольна будущей профессий, я планирую быть финансовым директором. Плюсы в том, что я буду знать, как работает экономика, откуда берутся деньги, планировать свой собственный бюджет. Минусов я пока не нашла. Процесс обучения проходит очень хорошо, наши преподаватели объясняют нам, пока вся группа не поймет материал. Любимый преподаватель – Казачков Владимир Александрович, он также мой научный руководитель по курсовой работе и мой куратор. Этот человек первым мне позвонил из ВУЗа и сказал, что я прохожу на эту специальность. Любимый предмет – английский язык, потому что мне нравится изучать языки. МГИМО для меня был идеальным вариантом, потому что я хотела изучать как экономику, так и языки. Группа очень дружная, мы поздравляем друг друга с днем рождения, делаем сюрпризы, вместе ходим на пары, смеемся, поэтому атмосфера очень дружелюбная. Планы на будущее – хочу​ попробовать работать как в МГИМО, так и в других​ компаниях, я надеюсь, что меня отправят на практику, где я покажу себя с лучшей стороны и останусь там работать.

**Comment by MariSh178** [comment]
Расшифровка интервью с Миленой.
Здравствуйте! Меня зовут Панасюк Милена, я студентка МГИМО. Я очень отзывчивый, открытый, позитивный человек. Еще в 9-м классе я поехала сюда на день открытых дверей,​ и когда я вошла в ВУЗ, я влюбилась с первого взгляда и поэтому очень хотела сюда поступить. Специальность выбрала спонтанно, решила, что хочу заниматься экономикой, хочу понимать, как это все раюботает, откуда берутся деньги. Поэтому я сюда поступила. Я очень довольна будущей профессией, я планирую быть финансовым директором. Плюсы в том, что я буду знать, как работает экономика, откуда берутся деньги, планировать свой собственный бюджет. Минусов я пока не нашла. Процесс обучения проходит очень хорошо, наши преподаватели объясняют нам, пока вся группа не поймет материал. Любимый преподаватель – Казачков Владимир Александрович, он также мой научный руководитель по курсовой работе и мой куратор. Этот человек первым мне позвонил из ВУЗа и сказал, что я прохожу на эту специальность. Любимый предмет – английский язык, потому что мне нравится изучать языки. МГИМО для меня был идеальным вариантом, потому что я хотела изучать как экономику, так и языки. Группа очень дружная, мы поздравляем друг друга с днем рождения, делаем сюрпризы, вместе ходим на пары, смеемся, поэтому атмосфера очень дружелюбная. Планы на будущее – хочу​ попробовать работать как в МГИМО, так и в других​ компаниях, я надеюсь, что меня отправят на практику, где я покажу себя с лучшей стороны и останусь там работать.

**Comment by MariSh178** [comment]
Предлагаю так:
Еще в 9-м классе я приехала в МГИМО на день открытых дверей,​ и когда вошла в ВУЗ, то влюбилась с первого взгляда и очень захотела в него поступить. Специальность выбрала спонтанно, решила, что хочу заниматься экономикой, понять, как это работает, откуда берутся деньги, научиться планировать свой собственный бюджет.
Я планирую стать финансовым директором. 

Процесс обучения проходит легко, наши преподаватели объясняют нам материал, пока вся группа не поймет.
Любимый преподаватель – Казачков Владимир Александрович, он также мой научный руководитель по курсовой работе и мой куратор. Мой любимый предмет – английский язык. МГИМО для меня был идеальным вариантом, потому что я хотела изучать как экономику, так и языки. 
У нас очень дружная группа: мы поздравляем друг друга с днем рождения, делаем сюрпризы, вместе ходим на пары, смеемся, поэтому атмосфера очень дружелюбная. 
Мои планы на будущее – хочу​ попробовать работать как в МГИМО, так и в других​ компаниях, надеюсь, что меня отправят на практику, где я покажу себя с лучшей стороны и останусь работать.

**Comment by MariSh178** [comment]
Предлагаю так:
Еще в 9-м классе я приехала в МГИМО на день открытых дверей,​ и когда вошла в ВУЗ, то влюбилась с первого взгляда и очень захотела в него поступить. Специальность выбрала спонтанно, решила, что хочу заниматься экономикой, понять, как это работает, откуда берутся деньги, научиться планировать свой собственный бюджет.
Я планирую стать финансовым директором. 

Процесс обучения проходит легко, наши преподаватели объясняют нам материал, пока вся группа не поймет.
Любимый преподаватель – Казачков Владимир Александрович, он также мой научный руководитель по курсовой работе и мой куратор. 
Мой любимый предмет – английский язык. МГИМО для меня был идеальным вариантом, потому что я хотела изучать как экономику, так и языки. 
У нас очень дружная группа: мы поздравляем друг друга с днем рождения, делаем сюрпризы, вместе ходим на пары, смеемся, поэтому атмосфера очень дружелюбная. 
Мои планы на будущее – хочу​ попробовать работать как в МГИМО, так и в других​ компаниях, надеюсь, что меня отправят на практику, где я покажу себя с лучшей стороны и останусь работать.

**Comment by MariSh178** [comment]
Еще в 9-м классе я приехала в МГИМО на день открытых дверей,​ и когда вошла в здание, то влюбилась с первого взгляда и очень захотела сюда поступить. Специальность выбрала спонтанно - решила, что хочу заниматься экономикой, понять, как это работает, откуда берутся деньги, научиться планировать свой собственный бюджет.
Я планирую стать финансовым директором. 

Процесс обучения проходит легко, наши преподаватели хорошо и достаточно терпеливо объясняют нам материал. 
Любимый преподаватель – Казачков Владимир Александрович, он также мой научный руководитель по курсовой работе и мой куратор.
Мой любимый предмет – английский язык. МГИМО для меня был идеальным вариантом, потому что я хотела изучать как экономику, так и языки. 
У нас дружная группа: мы поздравляем друг друга с днем рождения, делаем сюрпризы, вместе ходим на пары, смеемся, поэтому атмосфера очень дружелюбная. 
Мои планы на будущее – хочу​ попробовать работать как в МГИМО, так и в других​ компаниях, надеюсь, что меня отправят на практику, где я покажу себя с лучшей стороны и останусь работать.

**Comment by MariSh178** [comment]
Я приехал учиться в МГИМО из города Дубна Московской области по совету подруги, которая учится здесь на втором курсе. Я выбирал между несколькими ВУЗами, и программа в МГИМО мне показалась самой удачной: здесь два дополнительных языка и не такая большая нагрузка по техническим предметам. Я учусь на первом курсе и из опыта предыдущего семестра могу сказать, что на довольно хорошем уровне преподается экономика, много информатики, программа составлена хорошо. Преподаватели дают все нужные материалы в электронном виде или кидают ссылки на них в интернете - это очень удобно. Судя по загруженности на первом курсе, свободного времени довольно много, есть и дистанционные дни, поэтому, если правильно составить график, то вполне можно совмещать учебу с работой. Возможно, я стал психологически более устойчив, начал жить один. Быть студентом - значит завести много новых знакомств, друзей.
