### ISSUE TITLE
Перенести ссылки на файлы о количестве заявлений

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#180]

**Comment by edyatl** [comment]
Файл content/ru/about/program.md в ветке preview отличался от ветки main, новый коммит https://github.com/edyatl/finec-mgimo.github.io/commit/ce3ee04b790559f7a2031d3432707d1970dd3eb9 со ссылками был на файл из main, конфликт при мёрдже в пользу файла из main.
