### ISSUE TITLE
Добавить видео интервью выпускников

### ISSUE THREAD

**Issue by MariSh178** [necelentano/finec-mgimo-v2#184]
https://www.youtube.com/watch?v=HXHCCUTva88

**Comment by epogrebnyak** [comment]
@MariSh178 - для размещения на сайт здесь не хватает текста 

Также нужны фамилии студентов

**Comment by MariSh178** [comment]
Выпускники магистратуры Финэк МГИМО Вартанян Эдуард, Новокшонов Павел, Ткаченко Павел, Серебряков Михаил. 

Видео

Выпускники магистратуры рассказали о том, как обучение повлияло на их профессиональный рост, что больше всего запомнилось за время учебы и поделились своими планами на будущее.
