### ISSUE TITLE
Новость VR в образовании 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#191]
Уважаемые коллеги, добрый день, мы пригласили одного из участников акселератора MGIMO Ventures для демонстрации возможностей виртуальной реальности в образовании.

Четверг 7 июня 2022 в 12.00 на кампусе Одинцово в зале библиотеки 

Supersonic VR, Евгений Кузнецов 

Платформа для тренировки коммуникативных навыков в виртуальной среде

Преподаватели/кафедры могут самостоятельно создавать интерактивные ролевые симуляции на различных языках для дополнения учебных программ практической частью и отслеживать результаты прохождения заданий. 

Взаимодействие с виртуальными персонажами происходит с помощью голоса в формате диалога: система распознаёт речь обучающегося, формирует  ответ, а также предоставляет результаты по прохождению симуляции.

Приглашаем принять участие! 

Презентация: https://drive.google.com/open?id=1r5f1EztohMvxEixQakoVmrxrLl1yCXKd

**Comment by MariSh178** [comment]
[https://docs.google.com/document/d/1sN7FmJhnNspckmiiVfTvDrj5GlDYSCeyPV2lQizVTB8/edit?usp=drivesdk]()

**Comment by MariSh178** [comment]
https://docs.google.com/document/d/1sN7FmJhnNspckmiiVfTvDrj5GlDYSCeyPV2lQizVTB8/edit?usp=drivesdk

**Comment by epogrebnyak** [comment]
- https://odin.mgimo.ru/nov-pod-mgimo/5536-vr-novaya-realnost-dlya-yazykovoj-podgotovki-i-trenirovki-kommunikativnykh-navykov
- https://mgimo.ru/about/news/departments/vr-supersonic/
