### ISSUE TITLE
доработка карусели на первой странице

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#193]
Примеры фото для карусели

- Поздравляем выпускников 2022 года!
  - https://mgimo.ru/upload/iblock/b15/atk2sdaqx93d3wybpfavk24mwhugzv9g/odin-bac-dip-07-07-22.jpg 
  - https://finec.mgimo.ru/blog/graduates-2022/

- Корпоративный визит студентов Финэка в S8 Capital
  - https://finec.mgimo.ru/about/partners/finec-s8-capital_112.jpg
  - https://finec.mgimo.ru/about/partners/

- Проходим VR-тренинг от Supersonic VR (MGIMO Ventures)
  - https://mgimo.ru/upload/iblock/aef/qcs8hdeehk70kkccd9icg02z18f3gj7u/vr-odin-07-07-22-pr2.jpg
  - https://mgimo.ru/about/news/departments/vr-supersonic/

**Comment by epogrebnyak** [comment]
Нужен размер баннеров, которые подходят для карусели на первой странице

**Comment by epogrebnyak** [comment]
Closes #87 and closes #113

**Comment by super16** [comment]
@epogrebnyak размер баннеров желательно не больше 500px по ширине, по высоте не имеет значения, но важно, чтобы вся серия изображений были одного размера или, хотя бы, одной пропорции

**Comment by super16** [comment]
@epogrebnyak, добавил прототип карусели на стартовую в #198

**Comment by epogrebnyak** [comment]
> @epogrebnyak, добавил прототип карусели на стартовую в #197

@super16 - на каком-то отдельном бранче висит?

**Comment by super16** [comment]
В ветке [banner-carousel-193](https://github.com/finec-mgimo/finec-mgimo.github.io/tree/banner-carousel-193)

**Comment by epogrebnyak** [comment]
Карусель замержду в мейн, вижу два возможных улучшения:

- [x] сейчас положение кнопки прыгает из-за того, что размер картинок разный. Я уже спрашивал, но не помню - какой нам нужен размер картинки, чтобы кнопка всегда была на одном и том же месте?
- [ ] неинтуитивное размещение файлов - могут просто пути к yaml `/data/banners.yaml` и директории с картинками `/images/image-index/` быть параметрами шорткода?
- [x] незначительное: оставляет тонкую палку от одной из фото на другом, но это менять не будем

**Comment by super16** [comment]
@epogrebnyak 1 и 3 пункты поправил в #212, теперь высота всех изображений одинаковая, кнопка больше не «прыгает», тонкой полосы тоже больше не должно быть, это недочёт деления `calc` в CSS. 

По пункту два: путь к data файлу лучше не делать каким-то определённым с указанием расширения, так как архитектурой HUGO заложено, что data-файлы должны не зависеть от расширения, то есть [равнозначно может использоваться YML, TOML, XML, JSON](https://gohugo.io/templates/data-templates/#the-data-folder), одинаковые типы в data-файлах разных расширений обрабатываются одинаково. А также в шаблонах shortcodes неудобно обращаться к заданным путям и требуется дополнительная логика для их распарсивания и обработки, когда HUGO делает это всё автоматически.

**Comment by epogrebnyak** [comment]
> @epogrebnyak размер баннеров желательно не больше 500px по ширине, по высоте не имеет значения, но важно, чтобы вся серия изображений были одного размера или, хотя бы, одной пропорции

Спасибо, а понятно какой аспект нужен для возможного баннера или подбирать надо?

**Comment by epogrebnyak** [comment]
> По пункту два: путь к data файлу лучше не делать каким-то определённым с указанием расширения, так как архитектурой HUGO заложено, что data-файлы должны не зависеть от расширения, то есть [равнозначно может использоваться YML, TOML, XML, JSON](https://gohugo.io/templates/data-templates/#the-data-folder), одинаковые типы в data-файлах разных расширений обрабатываются одинаково. А также в шаблонах shortcodes неудобно обращаться к заданным путям и требуется дополнительная логика для их распарсивания и обработки, когда HUGO делает это всё автоматически.

Про пути понял, спасибо. Предлагаю в документации ответить про дефолтный путь этой карусели. Кстати класс карусели отличается на первой и не первой странице? Или это один и тот же?

**Comment by epogrebnyak** [comment]
> @epogrebnyak 1 и 3 пункты поправил в #212, теперь высота всех изображений одинаковая, кнопка больше не «прыгает», тонкой полосы тоже больше не должно быть, это недочёт деления `calc` в CSS.

В мобильном выглядят отлично, стабильно, ничего не скачет

**Comment by super16** [comment]
> какой аспект нужен для возможного баннера или подбирать надо?

Вероятно, желательно, тоже не больше ширины изображения. Квадратные и 4:3 изображения в узкой колонке смотрятся ок, вытянутые по высоте уже не очень

> Кстати класс карусели отличается на первой и не первой странице? Или это один и тот же?

Это два разных макроса, в документации я их разделил:

- [карусель](https://github.com/finec-mgimo/finec-mgimo.github.io/blob/main/docs/shortcodes.md#-%D0%BA%D0%B0%D1%80%D1%83%D1%81%D0%B5%D0%BB%D1%8C)
- [карусель с баннерами](https://github.com/finec-mgimo/finec-mgimo.github.io/blob/main/docs/shortcodes.md#--%D0%BA%D0%B0%D1%80%D1%83%D1%81%D0%B5%D0%BB%D1%8C-%D1%81-%D0%B1%D0%B0%D0%BD%D0%BD%D0%B5%D1%80%D0%B0%D0%BC%D0%B8)

**Comment by epogrebnyak** [comment]
Хочу заказать баннер, 400px на 300 px  будет хорошо?

**Comment by super16** [comment]
Лучше тогда ориентироваться на 500px на 375px, в идеале также иметь и большую версию 1000px на 750px

**Comment by epogrebnyak** [comment]
> 500px на 375px, в идеале также иметь и большую версию 1000px на 750px

Тогда будем ориентирвоаться на этот размер

**Comment by epogrebnyak** [comment]
Делаем первый баннер для карусели в #216
