### ISSUE TITLE
Приркепить фото участников крулого стола Digital CFO к новости в блоге

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#195]
https://mgimo.ru/about/news/announce/digital-cfo/

**Comment by epogrebnyak** [comment]
https://docs.google.com/document/d/1SQj9hU-cZFEQazfA8tp4nfKR6eh0x011pQR3KsNZ8jY/edit

**Comment by epogrebnyak** [comment]
@hel8er - могли бы перенести в новость, поменять размер и единообразно отобразить участников круглого стола в новости в блоге на нашем сайте?

https://finec.mgimo.ru/blog/digital-cfo-roundtable/

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/179355613-f1a91537-f017-414d-93e7-c1075f9abf82.png)

**Comment by epogrebnyak** [comment]
@hel8er - я посмотрел, что кругляшки лучше смотрятся вместе - нам нужен новый класс для аватара без обтекания и сдвига влево-вправо, могли бы посмотреть как его сделать?

**Comment by hel8er** [comment]
> @hel8er - я посмотрел, что кругляшки лучше смотрятся вместе - нам нужен новый класс для аватара без обтекания и сдвига влево-вправо, могли бы посмотреть как его сделать?

Принял
