### ISSUE TITLE
Перенести новость в блог: Настя об 1С

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#196]
https://odin.mgimo.ru/nov-pod-mgimo/5289-studentka-fakulteta-finansovoj-ekonomiki-anastasiya-pantyukhova-stala-finalistkoj-mezhdunarodnogo-professionalnogo-konkursa-po-1s-bukhgalterii-8

**Comment by epogrebnyak** [comment]
- пулл реквест на ветку preview 
- draft: false 
- обтекание фото как в новости о Данииле 
- внизу - оригинал новости в формате Alert
- прогнать через npm prettier

**Comment by ApogeeOfLabor** [comment]
Извиняюсь, поторопился с ПР. Ещё нужно немного времени.

**Comment by ApogeeOfLabor** [comment]
Непосредственно перенести не получлось, так как я не смог найти где лежат исходники статьи (вероятно их нет на github или у меня нет доступа к ним). 

В итоге скопировал данные с сайта по [ссылке Настя 1С](https://odin.mgimo.ru/nov-pod-mgimo/5289-studentka-fakulteta-finansovoj-ekonomiki-anastasiya-pantyukhova-stala-finalistkoj-mezhdunarodnogo-professionalnogo-konkursa-po-1s-bukhgalterii-8) и создал запись в блоге.

 - draft: false   -   учёл
 - обтекание фото как в новости о Данииле - вроде бы получилось
 - внизу - оригинал новости в формате Alert  -  не понял как это сделать
 - c Prettier пока тоже не получилось разобраться.
