### ISSUE TITLE
Перенести новость в блог: интервью с Марком

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#199]
https://prog.msk.ru/2020/11/19/how-programmer-can-teach-in-high-school/

дать дополнительную ссылку https://www.econ.msu.ru/students/bachelor/mng/Project-MAX/Article.20201017110630_5648/?ysclid=l5iqpmdh6i815816742

последовательность шагов такая как и в #196

**Comment by ApogeeOfLabor** [comment]
Не понял какое отношение к заданию имеет эта [https://prog.msk.ru/2020/11/19/how-programmer-can-teach-in-high-school/](https://prog.msk.ru/2020/11/19/how-programmer-can-teach-in-high-school/) ссылка)

**Comment by ApogeeOfLabor** [comment]
создал статью "Марк о языках" в блоге, закомитил, а она никак не хочет появляться в блоге на сайте(локальном) при запуске сервера (как-то странно, вроде всё так же делал как и с "Настя 1С")

**Comment by epogrebnyak** [comment]
@ApogeeOfLabor - вы не ту новость перенесли в блог и не той датой.

**Comment by epogrebnyak** [comment]
Также неудачная формулировка заголовка, не соотвествует другим новостям в блоге. 

@ApogeeOfLabor - это задание не нужно исправлять, оставлю открытым для других исполнителей.

**Comment by ApogeeOfLabor** [comment]
> Также неудачная формулировка заголовка, не соотвествует другим новостям в блоге. 
> 
> @ApogeeOfLabor - это задание не нужно исправлять, оставлю открытым для других исполнителей.

Ок

**Comment by epogrebnyak** [comment]
@elisad5791 - вы сделали коммит на своем форке, он пока никак не отразится на этом репо, для этого вам нужно сделать пулл реквест после обновления у себя 

Перед работой необходимо написать в ишью,что вы собираетесь его сделать.

Комментарии к коммиту по доработке контента

**Comment by elisad5791** [comment]
Контент доработала. Не очень понятна ситуация с большим количеством коммитов в пулл-реквесте. Но вы вроде их уже влили в preview, как я понимаю.

**Comment by elisad5791** [comment]
Или надо закрыть текущий пулл-реквест и сделать другой - без форка?

**Comment by epogrebnyak** [comment]
> Контент доработала. Не очень понятна ситуация с большим количеством коммитов в пулл-реквесте. Но вы вроде их уже влили в preview, как я понимаю.

Источник коммитов - это расхождение бранчей main и preview, хотя бы понятно откуда они взялись. Надо получше продумать инструкцию по PR c  форков.

**Comment by epogrebnyak** [comment]
> Или надо закрыть текущий пулл-реквест и сделать другой - без форка?

Вы без форка не сможете, так как не внутри репо, не будет прав доступа
