### ISSUE TITLE
можем ли использовать тему doks как submodule?

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#20]
так мы сможем ее обновлять по мере обновления основной темы и не надо в корне держать все что связано с npm

**Comment by necelentano** [comment]
Если честно, не особо знаком с таким подходом. В гугле нашлась статья где описан такой подход. В самом начале статьи автор пишет "Working with Hugo themes as git submodules is a pain". [Источник](https://www.hugofordevelopers.com/articles/master-hugo-modules-managing-themes-as-modules/)

**Comment by epogrebnyak** [comment]
Есть еще child theme, но я не очень понимаю, чем она от основного темплейта doks отличается

Блог с релизом child theme: 
- https://getdoks.org/blog/doks-v0.2/

Непонятно как использовать child theme:
- https://github.com/h-enk/doks/discussions/147#discussioncomment-509253
