### ISSUE TITLE
сделать драфт транскрипта круглого стола

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#200]
@Ydvornikova1 - ждем ссылку на видео 

@hel8er - могли бы черновик субтитров вытащить из видео?

**Comment by epogrebnyak** [comment]
https://www.youtube.com/watch?v=EjS7SpadOqg

**Comment by epogrebnyak** [comment]
```
youtube-dl --write-sub --write-auto-sub --skip-download EjS7SpadOqg
```

генерирует с таймстампами, нужно без

**Comment by epogrebnyak** [comment]
https://github.com/ytdl-org/youtube-dl/issues/17178

**Comment by epogrebnyak** [comment]
https://gist.github.com/glasslion/b2fcad16bc8a9630dbd7a945ab5ebf5e

**Comment by epogrebnyak** [comment]
```
youtube-dl --write-sub --write-auto-sub --skip-download --sub-lang ru EjS7SpadOqg -o subs
python vtt.py subs.ru.vtt
```

**Comment by epogrebnyak** [comment]
Next: таймкоды выступлений в видео 

ММ:SS Джанлука Бишеле
ММ:SS Следующий спикер

**Comment by elisad5791** [comment]
Основные спикеры 
03:06 Джанлука Бишеле
11:56 Лариса Ефремова
24:47 Ольга Чумаченко
32:35 Юлия Лелина
45:22 Ирина Одинаева
52:35 Петр Дорожкин
1:08:33 Олег Мазуров
1:19:59 Алексей Калашников
1:31:01 Андрей Карин
1:35:37 Сергей Гуртиков
1:39:18 Наталья Васильцова
1:41:53 Юлия Дворникова

**Comment by elisad5791** [comment]
Если нужны подробные тамкоды, то так:

00:00 Евгений Погребняк
03:06 Джанлука Бишеле
10:53 Евгений Погребняк
11:56 Лариса Ефремова
24:13 Евгений Погребняк
24:47 Ольга Чумаченко
31:05 Евгений Погребняк
32:35 Юлия Лелина
40:53 Евгений Погребняк
41:33 Юлия Лелина
43:32 Евгений Погребняк
45:22 Ирина Одинаева
49:59 Евгений Погребняк
50:21 Ирина Одинаева
50:56 Евгенйи Погребняк
52:35 Петр Дорожкин
1:05:21 Олег Мазуров
1:05:43 Евгений Погребняк
1:06:19 Петр Дорожкин
1:06:56 Евгений Погребняк
1:08:33 Олег Мазуров
1:17:10 Евгений Погребняк
1:18:07 Олег Мазуров
1:18:40 Евгений Погребняк
1:19:59 Алексей Калашников
1:26:41 Евгений Погребняк
1:27:02 Алексей Калашников
1:29:40 Евгений Погребняк
1:31:01 Андрей Карин
1:34:13 Евгений Погребняк
1:35:37 Сергей Гуртиков
1:37:24 Евгений Погребняк
1:38:23 Сергей Гуртиков
1:38:35 Евгений Погребняк
1:39:18 Наталья Васильцова
1:39:34 Евгений Погребняк
1:40:25 Наталья Васильцова
1:40:45 Евгений Погребняк
1:41:53 Юлия Дворникова
1:43:39 Евгений Погребняк

**Comment by epogrebnyak** [comment]
https://github.com/ytdl-org/youtube-dl

**Comment by epogrebnyak** [comment]
- [x] Драфт расшифровки https://docs.google.com/document/d/1tb2AtVYTFEGSv2DoGs_afz0rIofOkWngtpjMbG3v-mU/edit#
- [x] Таймкоды видео https://www.youtube.com/watch?v=EjS7SpadOqg

![изображение](https://user-images.githubusercontent.com/9265326/179370783-8bd4b5d5-03ba-4633-b596-f39a2ebb5e6c.png)
