### ISSUE TITLE
скрпит для исправления всех кавычек из елочек в прямые 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#207]
`«` -> `"`
`»` -> `"`

- [ ] Нужна команда для изменения кавычек в папке content на прямые 
- [ ] Добавить эту команду в just prettier в justfile (в корне проекта)

**Comment by immat0x1** [comment]
for i in $(grep -Ril -e "»" -e "«" content); do sed -i 's/«/"/g; s/»/"/g' $i; done

**Comment by immat0x1** [comment]
![IMG_20220716_130959_101](https://user-images.githubusercontent.com/73192010/179346500-24aa1953-a06f-41f4-8517-6e9d1cea18b4.jpg)
работает.

**Comment by epogrebnyak** [comment]
@immat0x1 - может как-то упростить можно?

**Comment by epogrebnyak** [comment]
Нужно что-то что из командной строки будет работать

**Comment by immat0x1** [comment]
`find content -type f -exec sed -i 's/«/"/g; s/»/"/g' {} \;`

можно так, но работает значительно дольше

**Comment by epogrebnyak** [comment]
Нужно только .md файлы менять, сейчас и jpeg корежит )

**Comment by epogrebnyak** [comment]
Скорость не так важна, читаемость  с find лучше

**Comment by immat0x1** [comment]
find content -type f -name "*.md" -exec sed -i 's/«/"/g; s/»/"/g' {} \;

теперь фотки не ест

**Comment by epogrebnyak** [comment]
Что-то не проходит:

```
root@LAPTOP-E0HT1CM9:/mnt/q/finec# find content -type f -name "*.md" -exec sed -i 's/«/"/g; s/»/"/g' {} ; 
find: missing argument to `-exec'
```

**Comment by epogrebnyak** [comment]
Со слешем работает:

find content -type f -name "*.md" -exec sed -i 's/«/"/g; s/»/"/g' {} \\;

**Comment by immat0x1** [comment]
гитхаб слэш съедает, в конце перед ; он обязательно должен быть

**Comment by epogrebnyak** [comment]
> гитхаб слэш съедает, в конце перед ; он обязательно должен быть

Да, точно - гитхаб съедает

**Comment by epogrebnyak** [comment]
@immat0x1 - спасибо за скрипт
