### ISSUE TITLE
страница с логотипами

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#21]
Перенести страницу с логотипами на finec-mgimo-v2 из https://github.com/finec-mgimo/finec-mgimo.github.io/blob/master/docs/logo.md - он же - https://finec.mgimo.ru/logo/

Картинки видимо в static положить надо.

Адрес на finec-mgimo-v2  не понятен, у нас обязательно должны быть странциы в ru и en? Можно по временному адресу разместить.

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/finec_logo.png)

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/120894292-4ee7cf80-c620-11eb-93fc-2b42e1adceda.png)

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/120894332-86ef1280-c620-11eb-8e54-4528383d032e.png)

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/120894399-d46b7f80-c620-11eb-93c7-5ba0fb14adae.png)

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/120894431-fd8c1000-c620-11eb-94e6-479538415f8a.png)

**Comment by epogrebnyak** [comment]
Исходный вариант логотипа Финэка:

- [finec_logo.pptx](https://github.com/necelentano/finec-mgimo-v2/files/6602673/finec_logo.pptx)

**Comment by epogrebnyak** [comment]
Чек-лист, что хотим:

- [ ] перенести finec.mgimo.ru/logo сюда
- [ ] на первой странице логотипы дать двумя картинками, можно те же

Что не хотим:

- [ ] вставлять логотип в верхний хедер (все поедет)
- [ ] использовать из лого github (добавлю потом)
- [ ] сгенерировать favicons (отдельным ишью)

**Comment by necelentano** [comment]
Добавил логотипы на главную.

**Comment by necelentano** [comment]
По поводу адреса finec-mgimo-v2. Если я сменю названия репо на finec-mgimo, то сайт автоматически соберется на новом адресе? В Github Actions не нужно будет ничего настраивать?

**Comment by epogrebnyak** [comment]
> По поводу адреса finec-mgimo-v2. Если я сменю названия репо на finec-mgimo, то сайт автоматически соберется на новом адресе? В Github Actions не нужно будет ничего настраивать?

Видимо соберется, Actions же просто билдит файлы для статического сайта и выкалдывает их в бранч gh-pages, никак при этом не затрагивая в каком репо это происходит.

Нюансы:

- [ ] адрес сайта где выкладыватеся нужно в настройках hugo менять (baseURL), а то сбилдится но будет не туда показывать (в итоге это будет finec.mgimo.ru)
- [ ] адрес поменять в пиктограмме гитхаба, чтобы на нужный репо показывал
- [ ]  у нас в Actions еще три левые какие-то работы лежат, нам только одна нужна

**Comment by epogrebnyak** [comment]
> Добавил логотипы на главную.

Все здорово, но на первой мне нужны два логотипа, а все коллекция - в https://github.com/necelentano/finec-mgimo-v2/blob/main/content/ru/logo.md ;)

**Comment by necelentano** [comment]
Может все таки коллекцию со всеми логотипам сделать как блогпост, а не страницу?
В принципе сделать Главную странице как превью разных секций сайта где будут ссылки на посты – Подраздел на главной "Логотипы ФИНЕК МГИМО" и там же "Больше информации здесь" и ссылка на пост с логотипами. Также и с другими секциями "Поступление", а там сразу будут ссылки на посту с SEO заголовками "Документы для поступления ФИНЕК МГИМО". Главная будет в роли хаба по самым важным направлениям, а весь контент будет в постах. Плюс постов это удобство администрирования контента и отдельная ссылка, которую человек может легко поделиться, с конкретным контентом.

**Comment by epogrebnyak** [comment]
Главная - да, это такая страница, где ссылки на топовые материалы, в этом я
согласен, очень поддерживаю.

Я как-то не думал, что сборник логотипов может быть блог-постом. Можно
сделать так - текст со словами - мол вот такие у нас логотипы, в этом
случае такой, в этой случае такой  - это пост в блоге, но что-то мне
кажется что сам сбоорник логотипов можно и продублировать на стабильном
адресе finec.mgimo.ru/logo (я просто сам привык что там собирается). Вам не
очень нравится отдельно висящий файл в content?

**Comment by epogrebnyak** [comment]
jxtym - очень ))

вс, 6 июн. 2021 г. в 22:25, Evgeny Pogrebnyak ***@***.***>:

**Comment by epogrebnyak** [comment]
> В принципе сделать Главную странице как превью разных секций сайта где будут ссылки на посты 

> Главная будет в роли хаба по самым важным направлениям, а весь контент будет в постах. Плюс постов это удобство администрирования контента и отдельная ссылка, которую человек может легко поделиться, с конкретным контентом.

Это хорошие идеи!

**Comment by necelentano** [comment]
_Вам не очень  нравится отдельно висящий файл в content?_
Ну да, то есть у нас все страницы присутствуют в навигации например. Они по сути доступны со всех страниц сайта. Получается, что это будет страница Логотипы на которую можно попасть только с Главной.  Также бесконечно расширять навигацию в хедере, подозреваю, что вряд ли получится. Возможно в будущем еще придется что-то добавить в навигацию в header.

**Comment by epogrebnyak** [comment]
Мне не очень нравится, что logo.md нужно переводить на английский. Задумка logo.md что на нее вообще не надо ходить, это техническая страница, которая мне нужна, чтобы не искать логотипы откуда взялись и не объяснять откуда их взять. Если считаете более правильно - давайте пусть будет пост в блоге, если будет еще такий текнической информации копиться - сделает раздел.

**Comment by necelentano** [comment]
Мне кажется для страницы Логотипы  [https://necelentano.github.io/finec-mgimo-v2/logo/](https://necelentano.github.io/finec-mgimo-v2/logo/) тоже нужно будет делать EN версию. К тому же, получается, что для нее нужно руками добавить layout, потому что сейчас у нее с проблемы с версткой  – иконка Github съехала в левый край топ меню. Непонятно откуда эта страница берет layout, видимо из default.

**Comment by epogrebnyak** [comment]
> Также бесконечно расширять навигацию в хедере, подозреваю, что вряд ли получится. Возможно в будущем еще придется что-то добавить в навигацию в header.

У нас актуальный вопрос  - левый список сделать - у меня предложения в #23 - можете посмотреть?

**Comment by epogrebnyak** [comment]
> 
> 
> Мне кажется для страницы Логотипы https://necelentano.github.io/finec-mgimo-v2/logo/ тоже нужно будет делать EN версию. К тому же, получается, что для нее нужно руками добавить layout, потому что сейчас у нее с проблемы с версткой – иконка Github съехала в левый край топ меню. Непонятно откуда эта страница берет layout, видимо из default.

Еще один аргумент запихнуть logo.md  в блог - мы не знаем откуда layout сейчас для него и не хотим на это время тратить. Давайте поживет в блоге?

**Comment by epogrebnyak** [comment]
Майлстоун сделал, @necelentano посмотрите пожалуйста - можете ли сделать, чего из информации не хватает.

**Comment by necelentano** [comment]
Как вариант сделать еще одну страницу Логотипы (по аналогии с Контакты). Она будет доступна через топ меню. Layout сделать как у страницы Контакты или можно другой какой-то попробовать.

**Comment by epogrebnyak** [comment]
Не надо через меню, пожлауйста.

Хочется закрыть этот ишью, буду линковать комментарии в коде.

**Comment by epogrebnyak** [comment]
@necelentano  - смотрите есть коммит ffdfaa5  - он создает страницу с логотипами. В самой тексте странциы написано что там не хватает. Просьба перенесите туда недостающий контент, можете в тексте страницы прокомментировать.

**Comment by necelentano** [comment]
Добавил страницу с логотипами (для EN и RU). Через директорию + индексный файл – logo/index.md. Работает хорошо. Картинки положил в content/ru/logo

**Comment by epogrebnyak** [comment]
Разделите файл front_dash.png на две картинки?

**Comment by epogrebnyak** [comment]
Меня по этому ишью беспокоит:

- непонятно почему не видит папку static bda0c4d
  - что-то хитрое с baseURL - видимо Hugo понимает только `site.com` часть, но не `site.com/subsite/` 
- из-за этого мы дублируем картинки
- зачем нужна папка images?

Вопросы некритичные, на улучшение существующей версии.

**Comment by epogrebnyak** [comment]
http://localhost:1313/finec-mgimo-v2/finec-mgimo-footer.png и https://epogrebnyak.github.io/finec-mgimo-v2/logo/finec.png - это один и тот же файл или нет?

Может нам удалить https://epogrebnyak.github.io/finec-mgimo-v2/logo/finec.png или он для чего-то нужен?

**Comment by necelentano** [comment]
В принципе да, это можно удалить https://epogrebnyak.github.io/finec-mgimo-v2/logo/finec.png – этот лого используется только на странице /logo/.

Картинка http://localhost:1313/finec-mgimo-v2/finec-mgimo-footer.png используется в футере, это обрезанная версия finec.png.

**Comment by epogrebnyak** [comment]
Задал вопрос про baseURL: https://discourse.gohugo.io/t/figure-shortcode-cannot-find-image-in-static-folder-in-site-com-subsite-baseurl/33357

**Comment by epogrebnyak** [comment]
> Картинка http://localhost:1313/finec-mgimo-v2/finec-mgimo-footer.png используется в футере, это обрезанная версия finec.png.

И еще в правом сайд-баре )

**Comment by necelentano** [comment]
> И еще в правом сайд-баре )

возможно я ее использовал для двух мест) , типа "переиспольование компонента" и создает один запрос на сервер))

**Comment by epogrebnyak** [comment]
предлагаю на a6e96bbec7d1fd47c024fc884dd492bf3aa98457 остановиться - как ориентир на будущее - сделать как отдельный partial блок с логотипами

**Comment by epogrebnyak** [comment]
> Задал вопрос про baseURL: https://discourse.gohugo.io/t/figure-shortcode-cannot-find-image-in-static-folder-in-site-com-subsite-baseurl/33357

Предлагают кастомный shortcode написать: https://discourse.gohugo.io/t/figure-shortcode-cannot-find-image-in-static-folder-in-site-com-subsite-baseurl/33357/14?u=epogrebnyak

**Comment by epogrebnyak** [comment]
И отсюда видно, что с ссылками вопрос застарелый в Hugo: https://github.com/gohugoio/hugo/issues/7714

**Comment by epogrebnyak** [comment]
Нам всеиравно скоро на новый baseURL поэтому закрою
