### ISSUE TITLE
отсутствует шорткод для mermaid

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#210]
нам нужен тэг mermaid = true в front matter, сейчас такого нет - hugo не распознает ключ mermaid  в заголовке

Нужно для #192

**Comment by epogrebnyak** [comment]
Скорее проблема в отсутствии шорткода, а не поля в заголовке

**Comment by epogrebnyak** [comment]
https://getdoks.org/docs/how-to/extra-features/mermaid/

**Comment by elisad5791** [comment]
Взяла в работу.

**Comment by epogrebnyak** [comment]
@elisad5791 - просьба сделать на отдельном бранче в этом репо

**Comment by elisad5791** [comment]
там нужно при mermaid:true подключать скрипт mermaid в шаблоне. В каком? blog/single.html ?

**Comment by epogrebnyak** [comment]
Вопрос открытый, я не знаю.Если разберётесь - предложите, если нет -
разассайните себя из ишью, чтобы кто другой мог сделать.

Help wanted - это более сложные ишью в проекте, в отличие от good first
issue.

вс, 17 июл. 2022 г., 18:06 elisad5791 ***@***.***>:

**Comment by elisad5791** [comment]
Я сделала, как описано в документации. Но вот сам рабочий процесс не понимаю. Склонировала к себе, сделала ветку mermaid, внесла изменения. Хочу запушить
git push origin mermaid
Ругается, что прав нет.

**Comment by epogrebnyak** [comment]
> Я сделала, как описано в документации. Но вот сам рабочий процесс не понимаю. Склонировала к себе, сделала ветку mermaid, внесла изменения. Хочу запушить git push origin mermaid Ругается, что прав нет.

Поднял права, должно проходить.

Документация нацелена на внешний форк (внешние котрибьютеры делают форк и PR в preview, внутренние открывают бранчи и ревьюим в ишью, до PR), ее надо менять в рамках #208.

По workflow - лучше сначала спросить, с каким ишью нужна помощь - сейчас получается, что для не очень приоритетного ишью мы тратим фокус внимания.

**Comment by epogrebnyak** [comment]
@elisad5791 - если можете - переименуйте бранч, чтобы был с номером ишью (см #208)

**Comment by epogrebnyak** [comment]
@elisad5791 - где у нас теперь референс на коммит в ишью?

**Comment by epogrebnyak** [comment]
@super16:

- нам нужно сделать прототип странички с mermaid в #192
- [96a5620](https://github.com/finec-mgimo/finec-mgimo.github.io/commit/96a56206e340495c5c21fbb8efb936f76e547390) - предлагаемое изменение
- просьба проверить, нужно ли что-то изменить и доработать
- просьба мерджить с референсом на #192 и #210

**Comment by super16** [comment]
Доработал поддержку mermaid на оптимизированную (то как это реализовано в Doks), теперь поддерживается оба синтаксиса из [инструкции](https://getdoks.org/docs/how-to/extra-features/mermaid/):

```html
{{< mermaid class="bg-light text-center" >}}
graph TD
  A[Hard] -->|Text| B(Round)
  B --> C{Decision}
  C -->|One| D[Result 1]
  C -->|Two| E[Result 2]
{{< /mermaid >}}
```

````markdown
```mermaid
graph TD
  A[Hard] -->|Text| B(Round)
  B --> C{Decision}
  C -->|One| D[Result 1]
  C -->|Two| E[Result 2]
```
````

Теперь поддержка mermaid берётся не из публичного CDN, а генерируется во время сборки сайта, а также CDN не поддерживает Markdown-синтаксис. В макросе mermaid также можно передавать собственные CSS-классы.

**Comment by super16** [comment]
Соответственно, в песочнице добавил [примеры из инструкции](https://github.com/finec-mgimo/finec-mgimo.github.io/blob/main/content/ru/sandbox/mermaid.md) и наработки из #192, а также рендеринг: https://finec.mgimo.ru/sandbox/mermaid/

**Comment by epogrebnyak** [comment]
@super16 - спасибо, то что нужно
