### ISSUE TITLE
показывать страницу контакты вместе с левым боковиком

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#22]
Когда мы нажимаем https://necelentano.github.io/finec-mgimo-v2/contacts/, то контакты показывают без левого боковика?

Что определяет как выглядит контакты? Сложно ли нам показывать с боковиком?

**Comment by necelentano** [comment]
Если честно не понимаю, почему не работает разметка для страницы Контакты, которую добавляем в layouts/_contacts/single.html. Как будто hugo или тема doks просто не видят этот layout. 
Если вставить разметку с сайдбаром (из layouts/docs/single.html) в layouts/_default/single.html то на странице Контакты появляется оба сайдбара (слева и справа).
Выглядит это так.
![contacts-w-sidebar](https://user-images.githubusercontent.com/20335885/120927827-e580c300-c6ea-11eb-83d6-3a74837b42de.jpg)

**Comment by epogrebnyak** [comment]
@necelentano  - этот вопрос решили, закрываем?

**Comment by necelentano** [comment]
нам нужен сайдбар (слева-справа) на странице Контакты?
