### ISSUE TITLE
на странице туризма исправить фото

### ISSUE THREAD

**Issue by Ydvornikova1** [necelentano/finec-mgimo-v2#223]
убрать лого СГУ и упоминания о совместной программе 
![issue](https://user-images.githubusercontent.com/84345357/212470418-80b9f0c6-2505-42f4-9220-720c020bdb28.jpg)

**Comment by Niellony** [comment]
![tourism](https://user-images.githubusercontent.com/84086618/212622583-16dbef15-eb06-4beb-8ff5-f0b1149e3dba.png)
