### ISSUE TITLE
Добавить на страницу "Менеджмент в креативных индустриях"

### ISSUE THREAD

**Issue by Niellony** [necelentano/finec-mgimo-v2#227]

**Comment by epogrebnyak** [comment]
На страницу по менеджменту

https://github.com/finec-mgimo/finec-mgimo.github.io/blob/main/content/ru/program/undergrad/management.md

надо добавить в маркдауне данные из 

https://docs.google.com/document/d/1qvyRjpyFDEDXXXyeBeAsPdJI6zlFRhDt/edit?usp=sharing&ouid=106505037879293427269&rtpof=true&sd=true

с учетом шаблонов из других страниц.

Также поменять руководителя - это не М.С.Романов.
