### ISSUE TITLE
левый сайдбар (docs) 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#23]
Предлагаю в левом сайдбаре (он называется кажется docs) сделать список наших программ:

```
Бакалавры
- Экономика -> program/feft
- Менеджмент -> program/fm
- Бизнес-информатика -> program/itmb

Магистры 
- Экономика фирмы и ВЭД  -> program/efved
- Искуственный интеллект -> program/ai
- Экономика IT и управление данными -> program/eit
```

Нам нужна папка content/program и там файлы с названиями программ + _index.md

Качество названий (помечены устоявшиеся):

- [x] program/feft
- [x] program/fm
- [x] program/itmb
- [x] Экономика фирмы и ВЭД  -> program/efved
- [x] Искуственный интеллект -> program/ai
- [x] Экономика IT и управление данными -> program/eit

**Comment by necelentano** [comment]
Тоже сейчас занимаюсь. Пока не могу разобраться. Вроде все работает, но почему то на некоторых страницах хедер некорректно отображается (один div исчезает и верстка в хедере ломается). Пробовал делать разные папки для Бакалавров и Магистров.

**Comment by epogrebnyak** [comment]
У меня вопрос ;) Откуда сайт может брать старый боковик (да еще с измененными путями), если мы его убрали из menu.*.toml

![изображение](https://user-images.githubusercontent.com/9265326/120940926-76c25a80-c728-11eb-96bb-a5ee49ea13f8.png)

**Comment by epogrebnyak** [comment]
> Пробовал делать разные папки для Бакалавров и Магистров.

Я папки сделал - program/undergrad и program/masters

**Comment by necelentano** [comment]
Может нужно нужно удалить _docs?
И в layout скорее всего нужно скопировать файлы list и single из docs в новь созданную program.

**Comment by necelentano** [comment]
Добавил программы в левый сайдбар.

**Comment by necelentano** [comment]
Дополнил длинные названия для программ в EN версии. Обновил menus.toml для обоих версий. 
На заметку. Вероятно верстка в хедере ломается из-за того, что нет EN версии страницы (либо названия файлов страницы на разных языках не соответствуют).

**Comment by epogrebnyak** [comment]
Сайдбар мы понимаем как работает, нужен формат для описания программ - #29
