### ISSUE TITLE
Устаревшая среда ubuntu-18.04

### ISSUE THREAD

**Issue by Niellony** [necelentano/finec-mgimo-v2#231]
This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023. For more details, see https://github.com/actions/runner-images/issues/6002

The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002

**Comment by epogrebnyak** [comment]
можно наверное также `ubuntu-latest` использовать
