### ISSUE TITLE
Создать раздел с преподавателями

### ISSUE THREAD

**Issue by Niellony** [necelentano/finec-mgimo-v2#232]
[Цифровые финансы_2023 новая.pptx](https://github.com/finec-mgimo/finec-mgimo.github.io/files/11284145/_2023.pptx)

**Comment by epogrebnyak** [comment]
Осип Бурлов (Zuzan)
Стартапы - Финтех - Рынки Азии

Руслан Гулевич (Илим)
Цифровая трансформация - Словарь бизнеса

Захар Калмыков (ГК Родина)
Цифровой финдиректор - Digital CFO  

Владимир Козлов (ИД Регламаент)
Управление рисками - Управление данными

Иван Коршиков (Тинькофф)
Финансовые рынки - Валютный трейдинг

Юлия Лебедева (...)
Корпоративные финансы

Мария Маракуева (ЕУ)
Управление рисками - Бановские технологии

Александр Полудницын (НСПК)
Платежные системы

Виктория Федотова (Мастерчейн)
Цифровые финансовые активы

Дмитрий Якубовский (Сбер)
ИТ в банках - Старт карьеры

---

**Comment by epogrebnyak** [comment]
Может быть сначала список без фото вывесить, определиться где он высвечивается у нас, в какой части сайта и потом фото добавлять

**Comment by epogrebnyak** [comment]
Можно также ссылки на новости до фото
