### ISSUE TITLE
проект первой страницы 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#24]
Нужна первая старнциа, которую можно показывать в качестве драфта макета.

На ней может быть два логотипа и несколько подзагловоков.

**Comment by necelentano** [comment]
Добавил пару логотипов на главной (обе версии RU и EN). Поместил картинки в корень директории content/en (по аналогии как это работает с картинками в блогпостах) откуда их подхватывает content/en/_index.md. Логотипы есть только в content/en, но они отображаются и на RU версии.

**Comment by epogrebnyak** [comment]
> Поместил картинки в корень директории content/en (по аналогии как это работает с картинками в блогпостах) откуда их подхватывает content/en/_index.md. Логотипы есть только в content/en, но они отображаются и на RU версии.

Мне кажется как-то неинтуитивно - основная русская - картинки в англйиской. Может в `static` проще их переложить?
Оттуда должны подцепляться.

**Comment by epogrebnyak** [comment]
Сейчас по структуре меня _index.md устривает (про оформление и наполнение - отдельно), @necelentano - как вам?

**Comment by necelentano** [comment]
> Мне кажется как-то неинтуитивно - основная русская - картинки в англйиской. Может в `static` проще их переложить?
> Оттуда должны подцепляться.

Тогда можно в RU поместить. К сожалению через static картинки работали только на RU версии, а на EN версии не загружались и к сожалению не разобрался как сделать что бы это работало для обоих версий. 
Считаю нормальным держать контент который касается конкретной страницы рядом с самой страницей. Это удобно и понятно – если файлы лежат в какой-то директории, значит они связаны с контентом в этой директории. К тому же картинки будут автоматом подхватываться для этого поста/страницы на другом языке (насколько помню это работало именно так).

**Comment by necelentano** [comment]
> Сейчас по структуре меня _index.md устривает (про оформление и наполнение - отдельно), @necelentano - как вам?

да, симпатично выглядит.
