### ISSUE TITLE
edit this page on github - указывает на неверную ссылку

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#26]
Правильный адрес:

https://github.com/necelentano/finec-mgimo-v2/blob/main/content/ru/program/masters/artificial-intelligence.md

Куда показывает (нет ru):

https://github.com/necelentano/finec-mgimo-v2/blob/main/content/program%5Cmasters%5Cit-economics-data-management.md

**Comment by epogrebnyak** [comment]
https://github.com/necelentano/finec-mgimo-v2/blob/e3bc2f8ff4b4c34f220cc9b898bb50fde819a244/config/_default/params.toml#L39-L41

**Comment by epogrebnyak** [comment]
https://github.com/h-enk/doks/issues/314

**Comment by epogrebnyak** [comment]
We can set  `editPage = false` if no easy  solution found

**Comment by necelentano** [comment]
I will try to research this topic.
