### ISSUE TITLE
запрос по описанию программы

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#29]
Сейчас в `content/program` у нас в сумме 6 пусты[ файлов. Нужна общая структура для этих файлов, по возможности простая (хотим меньше дублировать, если есть материал еще где-то - дать ссылку).  

- Название программы
- Направление 
- Количество мест
- Бюджетные места
- Стоимость обучения
- Как поступить
- Профиль выпускников
- Документы программы
- Ссылка на приемную комиссию
- Интервью и материалы
- Изучаемые предметы

**Comment by epogrebnyak** [comment]
@veronmolosh - можете в https://github.com/necelentano/finec-mgimo-v2/blob/main/content/ru/program/undergrad/finec-fintech.md сделать драфт описания программы по примерному формату выше, используя информацию из http://pk.odin.mgimo.ru/bakalavriat/fim.html (исправлено).

**Comment by epogrebnyak** [comment]
Что-то из коротких элементов описания можно использовать отсюда: https://event.mgimo.ru/

**Comment by veronmolosh** [comment]
* Переход на сайт pk можно сделать кнопкой
* Таблица возможно лучше html
* Образец договора под вопросом
* Фото руководителей
* Презентация программы
* Больше интервью
* Материалы студентов
* [Бэдж для ЕГЭ](https://shields.io/category/build)

**Comment by epogrebnyak** [comment]
content/ru/program/undergrad/finec-fintech.md  - страница выгляди не на своем месте, сейчас переставлю

**Comment by epogrebnyak** [comment]
@veronmolosh - могли бы этот раздел сделать плс?

![изображение](https://user-images.githubusercontent.com/9265326/121789968-43c60e00-cbe3-11eb-8c07-3ef5b4c603b3.png)

**Comment by epogrebnyak** [comment]
Текущий формат описания программы: https://github.com/epogrebnyak/finec-mgimo-v2/blob/cb373842ff814fc64b57e58009d68f1a199892e5/content/ru/program/undergrad/finec-fintech.md

**Comment by epogrebnyak** [comment]
Дополнительные вопросы.

1. Коротко о программе: когда, в каких условиях появилась; с какой целью создавалась.
2. Уникальность программы, ее отличие от аналогичных и похожих.
3. Профилирующие дисциплины в рамках программы и (если известны) педагоги со званиями и регалиями
4. Потенциальные работодатели выпускников программы
5. Условия поступления и даты подачи документов.
6. Контактная информация.
