### ISSUE TITLE
первая страница сайта

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#34]
@necelentano - у нас открытый вопрос, что лучше сделать с логотипами на первой странице:

- разрезвать на две картинки, уменьшить, оставить там же
- перенести в контейнер "Содержание" - с одной стороны он самостоятельный, с другой сторны содеражние тоже полезно
- какой-то еще вариант?

Я разобрал по разделам материал с первой страницы, чтобы было почище сейчас.

**Comment by epogrebnyak** [comment]
Дополнительная идея: на первой странице можно давать заголовки блогов (два вида информации - ссылки на топовоые неблоговые материалы или анонсы и блоги).

**Comment by necelentano** [comment]
Если честно, то я бы оставил одну картинку с двумя лого. Одна картинка легче адаптируется под разные экраны и стили уже написаны для этого (конкретно под мобильный не нужно городить костыли с wrapper'ом двух картинок или таблицей). Не уверен, что фактор производительности (performance) так важен для текущего проекта, но одна картинка создает один запрос на сервер, две картинки = два запроса. 
Как я уже упоминал блок Содержание не отображается на мобильных – логотипов на мобильных не будет, если разместить лого в Содержание.

**Comment by epogrebnyak** [comment]
> Если честно, то я бы оставил одну картинку с двумя лого. 

Может мы тогда уменьшим ее размер, примерно 75% от текущего?

**Comment by epogrebnyak** [comment]
По размеру мне нравится! А обтекание текстом нам ничего не даст?

**Comment by epogrebnyak** [comment]
Кстати 75% - это от чего сейчас - ширины экрана или исходного размера картинки?

**Comment by epogrebnyak** [comment]
Что-то глядя на ca26163 первая страница меня не вдохновляет. Верстка используется разряженная, текст, который мы будем на первую ставить - займет много места.

Нам может быть какую-то качественную фотографию большую на первой странице размещать?

Логотипы на экране просятся вбок, вместо содержания (ну не увидят на мобильных их)

**Comment by epogrebnyak** [comment]
Содержание не очень клеится потому что H1/H2 заголовки дико большие для этой страницы, а заголовки более низких уровней - не увидят.

В конце концов можно потом для мобильной версии как-то переделать, чтобы картинки показывались, уже на новых этапах.

**Comment by necelentano** [comment]
Добавил логотипы в правый сайд бар, в этой реализации логотипы будут на каждой странице где есть этот сайдбар. 


> Содержание не очень клеится потому что H1/H2 заголовки дико большие для этой страницы, а заголовки более низких уровней - не увидят.

Размер заголовков можно уменьшить.

**Comment by epogrebnyak** [comment]
Отклеилась картинка в футере мне кажется

**Comment by necelentano** [comment]
Да, сразу заметил) Пофиксил.

**Comment by epogrebnyak** [comment]
Мне хочется поупралять показываем мы содержание или нет - отдельный ишью здесь: https://github.com/epogrebnyak/finec-mgimo-v2/issues/48

**Comment by epogrebnyak** [comment]
У нас сейчас получается что даже если заголовков нет, то слово "Содержание" - висит всегда, не очень красиво.

В идеале (подумать, не корежит ли верстку):

- мы поставили логотипы на первую страницу справа
- мы можем включать-выключать содержание через `toc = true` или `toc = false`

Логотипы на первую страницу - насколько сложно сделать должен быть самостоятельным блоком  для перво старницы, без внедрения в partial toc? сверху справа блок в логотипа, снизу блок toc - на последующих страницах блока с логотипом нет - насколько это сложно?

**Comment by epogrebnyak** [comment]
фактически - внедрить в index.html лготипы напрямую, вне toc-partial'а?

**Comment by necelentano** [comment]
> фактически - внедрить в index.html лготипы напрямую, вне toc-partial'а?

вроде да, можно вставить их в layouts/index.html. И логотипы будут отображаться только на главной.

**Comment by epogrebnyak** [comment]
> вроде да, можно вставить их в layouts/index.html. И логотипы будут отображаться только на главной.

Да, давайте так сделаем, для неглавных страниц у нас будет футер с логотипом.

**Comment by necelentano** [comment]
Вставил логотипы в layouts/index.html.
Теперь логотипы в правом сайдбаре отображаются только на Главной странице.

**Comment by epogrebnyak** [comment]
> Вставил логотипы в layouts/index.html.
> Теперь логотипы в правом сайдбаре отображаются только на Главной странице.

Спасибо, посмотрел. Сейчас `toc = false` в _index.md убирает логотипы, они могут быть от него независымы?

**Comment by epogrebnyak** [comment]
Визуально они больше стали по размеру (что может и неплохо)

**Comment by necelentano** [comment]
По идее сделал как нужно.

**Comment by necelentano** [comment]
> Визуально они больше стали по размеру (что может и неплохо)

стили не трогал. По идее все должно оставаться как и прежде. Может попробовать кэш сбросить?

**Comment by epogrebnyak** [comment]
> По идее сделал как нужно.

Предлагаю на a6e96bbec7d1fd47c024fc884dd492bf3aa98457 остановиться, выглядит здорово.

Как ориентир на будущее - сделать как отдельный partial блок с логотипами - чтобы можно было включать или выключать.
