### ISSUE TITLE
npm run lint:markdown ругается на нашу разметку

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#36]
Попробовать прогнать content через https://prettier.io/docs/en/index.html, посмотреть уходят ли ошибки линтера

@oqsan-syan

**Comment by oqsan-syan** [comment]
На .md файлах были ошибки, я все исправила, по моему сейчас все норм, никаких ошибок в терминале нет npm run lint:markdown команда тоже не выдает ошибок .

_Были примерно такие ошибки_
![2021-06-09 (6)](https://user-images.githubusercontent.com/69961539/121410173-5e924b80-c973-11eb-8aee-288cee86308a.png)

![2021-06-09 (10)](https://user-images.githubusercontent.com/69961539/121410343-8bdef980-c973-11eb-9fdb-a2c7a0ba588a.png)

**Здесь уже введена команда и все чисто**
![2021-06-09 (18)](https://user-images.githubusercontent.com/69961539/121410380-939e9e00-c973-11eb-903a-9f423e36a635.png)

**Comment by epogrebnyak** [comment]
@oqsan-syan - удалось ли с prettier придумать вариант?

**Comment by epogrebnyak** [comment]
```npx prettier --write .```
