### ISSUE TITLE
наполнение раздела Люди

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#37]

**Comment by StazzTukma** [comment]
---
title: "Люди"
description: "Руководство и сотрудники факультета."
date: 2021-06-07
lastmod: 2021-06-07
draft: false
images: []
weight: 20
---

В штате факультета — 38 человек, из них 8 докторов и 27 кандидатов наук.

---
# Руководство факультета

## Погребняк Евгений Владимирович

### **Декан факультета**

<p style="float: left; padding-right: 20px"><img src="https://finec.mgimo.ru/people/img/thumbs/pogrebnyak.jpg" width="112px" height="150px"></p>
<br>

***Ученая степень***: Кандидат экономических наук

***Образование***: Экономический факультет МГУ им. М.В. Ломоносова

[Личная страница в разделе Люди А-Я](https://mgimo.ru/upload/iblock/341/pogrebnyak.jpg)

<br>

## Дворникова Юлия Владимировна

### **Заместитель декана**

<p style="float: left; padding-right: 20px"><img src="../../../static/people/dvornikova.jpg" width="112px" height="150px"></p>
<br>

***Ученая степень***: Кандидат экономических наук

<br><br><br><br><br>

---

# Руководители кафедр

## Саркисян Жаклин Меружановна

### **Заведующий кафедрой экономики и финансов**
<p style="float: left;margin-bottom: 1px; padding-right: 20px"><img src="https://mgimo.ru/upload/iblock/d77/%D0%A1%D0%B0%D1%80%D0%BA%D0%B8%D1%81%D1%8F%D0%BD%20%D0%96%D0%9C.jpg" width="112px" height="150px"></p>
<br>

***Ученая степень***: Кандидат юридических наук

***Образование***: МГИМО МИД России

Действительный государственный советник Российской Федерации 3 класса

[Личная страница в разделе Люди А-Я](https://mgimo.ru/people/sarkisyan-zhaklin/)

## Василюк Татьяна Николаевна

### **Заведующий кафедрой менеджмента**

<p style="float: left;margin-bottom: 1px; padding-right: 20px"><img src="https://mgimo.ru/upload/iblock/858/Vasilyuk.jpg" width="112px" height="150px"></p>
<br>

***Ученая степень***: Кандидат экономических наук

***Ученое звание***: Доцент

***Образование***: Экономический факультет МГУ им. М.В. Ломоносова

Стаж работы в высших учебных заведениях: с 1980 года

Научные и учебные издания: автор более 50 трудов.

[Личная страница в разделе Люди А-Я](https://mgimo.ru/people/vasilyuk/)

## Притчина Лариса Сергеевна

### **Заведующий кафедрой математических методов и бизнес-информатики**

<p style="float: left;margin-bottom: 1px; padding-right: 20px"><img src="https://mgimo.ru/upload/iblock/4fe/pritchina.jpg" width="112px" height="150px"></p>
<br>

***Ученая степень***: Кандидат технических наук

***Ученое звание***: Доцент

***Образование***: Государственный университет управления

Стаж работы по специальности - с 1983 года, стаж работы в МГИМО - с 2016 года.

Научные и учебные издания: автор более 70 трудов.

[Личная страница в разделе Люди А-Я](https://mgimo.ru/people/pritchina/)

## Абрамова Анна Владимировна

### **Заведующий кафедрой цифровой экономики и искусственного интеллекта**

<p style="float: left;margin-bottom: 1px; padding-right: 20px"><img src="https://mgimo.ru/upload/iblock/886/886ee3acf577dc8d005e2ad24615f1ff.jpg" width="112px" height="150px"></p>
<br>

***Ученая степень***: Кандидат экономических наук

***Ученое звание***: Доцент

***Образование***: МГИМО МИД России

[Личная страница в разделе Люди А-Я](https://mgimo.ru/people/abramova-anna/)

---

# Сотрудники деканата

## Белобосова Наталия Сергеевна

<p style="float: left;margin-bottom: 1px; padding-right: 20px"><img src="https://mgimo.ru/upload/iblock/479/belosobova%20natalia.png" width="112px" height="150px"></p>
<br>

Специалист по учебно-методической работе факультета финансовой экономики

Стаж работы в МГИМО — с 2016 года.

<br>

## Насырова Светлана Леонидовна

<p style="float: left;margin-bottom: 1px; padding-right: 20px"><img src="https://mgimo.ru/upload/iblock/080/nasirova.jpg" width="112px" height="150px"></p>
<br>

Специалист по учебно-методической работе факультета финансовой экономики

Стаж работы в МГИМО — с 2016 года.

<br>

## Савельева Ольга Александровна

<p style="float: left;margin-bottom: 1px; padding-right: 20px"><img src="https://mgimo.ru/upload/iblock/3a9/o.saveljeva.jpg" width="112px" height="150px"></p>
<br>

Специалист по учебно-методической работе факультета финансовой экономики

Стаж научно-педагогической работы в высших учебных заведениях — с 2001 года.

<br><br>

---

# Сотрудники наших кафедр
#### — [Кафедра экономики и финансов](<https://mgimo.ru/study/faculty/ffe/kef/employees/>)
#### — [Кафедра менеджмента](<https://mgimo.ru/study/faculty/ffe/kmen/employees/>)
#### — [Кафедра математических методов и бизнес-информатики](<https://mgimo.ru/study/faculty/ffe/kmmbi/employees/>)
#### — [Кафедра цифровой экономики и искусственного интеллекта](<https://mgimo.ru/study/faculty/ffe/kafadv/employees/>)

См. также - <https://finec.mgimo.ru/people/departments>

**Comment by epogrebnyak** [comment]
@StazzTukma - можно перенести внутрь этого репо, можете сделать?

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/123514727-0cecff00-d69d-11eb-8924-268512c4a465.png)
