### ISSUE TITLE
перенести "Рассказывают студенты" в about

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#38]
Исходные материалы https://finec.mgimo.ru/dod/students/

- использовать shortcode youtube
- указать год выпуска вместо курса
- алфавитный порядок

**Comment by epogrebnyak** [comment]
@veronmolosh - можно это следующее сделать

**Comment by veronmolosh** [comment]
@epogrebnyak делаю интервью студентов в формате списка?

**Comment by veronmolosh** [comment]
Нужно переносить весь текст из "Рассказывают студенты"? Или достаточно ссылок на выступления?

**Comment by epogrebnyak** [comment]
@veronmolosh:

- [x] нужно перенести весь https://raw.githubusercontent.com/finec-mgimo/finec-mgimo.github.io/master/docs/dod/students.md
- [x] использовать shortcode youtube
- [x] указать год выпуска вместо курса 
- [x] алфавитный порядок

**Comment by epogrebnyak** [comment]
@veronmolosh: вам надо добавить front matter  в students.md, без него ничего показываться не будет

**Comment by epogrebnyak** [comment]
теги hugo для youtube, пример: `{{< youtube aJGMGFzMQLk >}}` (в interview.md)
