### ISSUE TITLE
Смена адресов 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#46]
@necelentano - просьба поменять на сайте URL в связи с переездом: 

- baseUrl
- read me 
- линки на гит в верху 
- линкм на гит редактирования

Может еще где-то

**Comment by necelentano** [comment]
Обновил все URL, которые есть в теме и контенте.

**Comment by epogrebnyak** [comment]
@necelentano - спасибо, повторим при переезде на основной сайт
