### ISSUE TITLE
как упралять блоком содержание?

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#48]
@necelentano - напомни, пожалуйста, что управляет блоком "Содерждание" - глобально или может ли изменяться для каждой страницы?

**Comment by epogrebnyak** [comment]
видимо `toc = true` или `toc = false` во front matter

**Comment by necelentano** [comment]
За блок Содержание отвечает layouts/partials/sidebar/docs-toc.html.
В текущей реализации он подключается на страницах типа docs и не меняется. Но наверняка есть возможность проверять  
на какой странице находится пользователь и подключать другую версию docs-toc.html.

**Comment by epogrebnyak** [comment]
> В текущей реализации он подключается на страницах типа docs и не меняется. 

docs-partial отвечает вообще за то что toc может выводится, а показывать или нет - видимо toc = true / false во front matter

Не очень понятно дефолтное значение toc правда где задается, но не столь важно.
