### ISSUE TITLE
в чем отличие derscription и lead во front matter?

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#49]
Где показываются, как влияют на SEO? lead - возможно это только для блогов?

**Comment by necelentano** [comment]
front matter description отображается как meta name="description". В принципе в SEO это еще может котироваться.
front matter lead просто рендерится на странице как обычный параграф. Его можно вообще не использовать и просто удалить из front matter (если нет планов на его использовать на страницах docs). Но для блога думаю он уместен.

**Comment by epogrebnyak** [comment]
Но для SEO - главное title, верно?

**Comment by necelentano** [comment]
> Но для SEO - главное title, верно?

Верно.
