### ISSUE TITLE
подобрать цвета для шилдов по ЕГЭ

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#50]
![изображение](https://user-images.githubusercontent.com/9265326/121789066-6fdd9100-cbdb-11eb-84db-21c612660ca3.png)

https://github.com/epogrebnyak/finec-mgimo-v2/blob/main/content/ru/program/undergrad/finec-fintech.md

**Comment by epogrebnyak** [comment]
@necelentano - можете цвета подобрать?

**Comment by necelentano** [comment]
понял, что цвета можно задавать кодом с примером на shields.io, но для чего подбирать цвета из описания задачи не понял ((

**Comment by epogrebnyak** [comment]
Цвет шилда должен не отпугивать студентов - может в одной гамме, может еще
по какому-то приниципу.

Формально - вопрос палиты цветов - как-то подходит по сайту.

Хотя - может просто все синие сделаем?

вс, 13 июн. 2021 г., 12:35 Андрей | Andrey ***@***.***>:

**Comment by necelentano** [comment]
> Хотя - может просто все синие сделаем?

Вроде нормальный вариант. Разные цвета дадут поступающим какую-то дополнительную информацию? Не уверен, что у учащихся есть какие-то ассоциации между учебном предметом и каким-то цветом, чтобы они увидели зеленый бейдж и сразу поняли – "Ага, нужна математика".
ИМХО, конечно.

**Comment by epogrebnyak** [comment]
Разные цвета дали бы информацию, когда мы сравниваем несколько программ,
тогда бы было видно - о, математика, математика, маткматика, а тут что-то
другое.

Но мы непонятно где будем сравнивать, поэтому цвета немного преждевременно.

вс, 13 июн. 2021 г., 15:47 Андрей | Andrey ***@***.***>:

**Comment by necelentano** [comment]
> Разные цвета дали бы информацию, когда мы сравниваем несколько программ, тогда бы было видно - о, математика, математика, маткматика, а тут что-то другое.

Тут, могу согласиться. Вероятно, в таком случае разные цвета будут работать. У меня нет всей картины по оформлению контента, по этому сужу только по каким-то типичным сценариям с точки зрения поступающих – нужно/полезно это будет им или нет.

**Comment by epogrebnyak** [comment]
Сделал все синие
