### ISSUE TITLE
неправильные кнопки влево-вправо внизу

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#51]
![изображение](https://user-images.githubusercontent.com/9265326/121953699-8e23c800-cd66-11eb-8c77-922ccca74e0b.png)

Документ относится к разделу undergrad, ссылки внизу ведут на раздел магиструтура, почему - непонятно.

**Comment by necelentano** [comment]
Да, там целая каша на всех страницах. Непонятно. Нужно будет покопаться.

**Comment by epogrebnyak** [comment]
> Да, там целая каша на всех страницах. Непонятно. Нужно будет покопаться.

Из того что приходит в голову:

- убрать неиспользуемые страницы md (черновики)
- посомтреть как в layout кнопки оформлены, что за код 
- отключить вообще эти кнопки - по-моему опция в меня есть

**Comment by epogrebnyak** [comment]
Ничего непонятно, но есть какой-то `{{ $pages := where site.RegularPages "Section" .Section -}}`

https://github.com/epogrebnyak/finec-mgimo-v2/blob/main/layouts/partials/main/docs-navigation.html

**Comment by epogrebnyak** [comment]
Еще вариант - написать в doks

**Comment by necelentano** [comment]
Смотрю сейчас. Там папка summary, она по структуре там нужна (по идее у summary должен быть свой раздел в левом меню, типа summary-id)? Также в файлах summary во front matter ошибки есть, но я вроде исправил, но все равно кашу не исправил. Нужно копаться.

**Comment by necelentano** [comment]
Вроде здесь обсуждают похожую проблему с вложенными секциями https://github.com/gohugoio/hugo/issues/5883

**Comment by necelentano** [comment]
Еще что-то. Не уверен что поможет в нашей задаче, но оставлю здесь, может пригодиться https://gist.github.com/rordi/eab8606b377638eeaa984367bde0a2d0

**Comment by necelentano** [comment]
Убираются эти кнопки в layouts/program/single.html – [эта строчка](https://github.com/epogrebnyak/finec-mgimo-v2/blob/main/layouts/program/single.html#L24).

**Comment by necelentano** [comment]
Вроде нашел на просторах интернета решение, которое работает. Завтра займусь.

**Comment by necelentano** [comment]
Добавил новую разметку в docs-navigation.html. Чтобы все работало как нужно, пришлось также изменить название индексного файла (program/masters/index.md => program/masters/_index.md). Иначе страница index.md (без нижнего подчеркивания) отображалась в кнопках навигации как и другие страницы секции masters.
