### ISSUE TITLE
Разместить ссылки на учебные планы по всем образовательным программам.

### ISSUE THREAD

**Issue by necelentano** [necelentano/finec-mgimo-v2#53]
Нужно разместить учебные планы образовательных программ в описании соответствующих разделов на сайте.

**Задачи**
1. Находить все документы с образовательными программами факультета;
2. Разместить ссылки с образовательными программами на сайте в соответствующих разделах/страницах.

Ниже будут добавлены примеры описания программ.

**Comment by epogrebnyak** [comment]
https://odin.mgimo.ru/sveden/education/

Раздел "Информация по образовательным программам" - собрать ссылки на программы факульетата:
- три бакалаврские  (туризм, финэкономика, ИТМБ, финменеджмент)
- три магистерские (экономика ИТ, ИИ, экономика фирмы)

Можно сделать раздел в /About, третья или четвертая сслылка по счету

**Comment by hel8er** [comment]
> Бакалавриат:

- Туризм (Туризм и индустрия гостеприимства) 2022: 
[ОПОП](https://odin.mgimo.ru/sveden/files/002622.pdf)
[Учебный план](https://odin.mgimo.ru/sveden/files/002623.pdf)
[Аннотации](https://odin.mgimo.ru/sveden/files/002269.pdf)

- Экономика (Финансовая экономика и финансовые технологии) 2021: 
[ОПОП](https://odin.mgimo.ru/sveden/files/002214.pdf)
[Учебный план](https://odin.mgimo.ru/sveden/files/002419.pdf)
[Аннотации](https://odin.mgimo.ru/sveden/files/002395.pdf)

- Бизнес-информатика (Информационные технологии в международном бизнесе) 2021: 
[ОПОП](https://odin.mgimo.ru/sveden/files/002226.pdf)
[Учебный план](https://odin.mgimo.ru/sveden/files/002227.pdf)
[Аннотации](https://odin.mgimo.ru/sveden/files/002400.pdf)

- Менеджмент (Финансовый менеджмент ) 2021: 
[ОПОП](https://odin.mgimo.ru/sveden/files/002221.pdf)
[Учебный план](https://odin.mgimo.ru/sveden/files/002222.pdf)
[Аннотации](https://odin.mgimo.ru/sveden/files/002269.pdf)

>  Магистратура:

- Бизнес-информатика (Экономика ИТ и управление данными) 2021: 
[ОПОП](https://odin.mgimo.ru/sveden/files/002383.pdf)
[Учебный план](https://odin.mgimo.ru/sveden/files/002462.pdf)
[Аннотации](https://odin.mgimo.ru/sveden/files/002384.pdf)

- Бизнес-информатика (Искусственный интеллект) 2021: 
[ОПОП](https://odin.mgimo.ru/sveden/files/002253.pdf)
[Учебный план](https://odin.mgimo.ru/sveden/files/002446.pdf)
[Аннотации](https://odin.mgimo.ru/sveden/files/002416.pdf)

- Экономика (Экономика фирмы и внешнеэкономическая деятельность) 2021: 
[ОПОП](https://odin.mgimo.ru/sveden/files/002564.pdf)
[Учебный план](https://odin.mgimo.ru/sveden/files/002445.pdf)
[Аннотации](https://odin.mgimo.ru/sveden/files/002414.pdf)

**Comment by epogrebnyak** [comment]
@hel8er - могли бы по этим программам - дать ссылки: на ОПОП и на учебный план?

- Туризм (Туризм и индустрия гостеприимства) 2022:
   - [ОПОП](...)
   - [Учебный план](...)
