### ISSUE TITLE
Сделать класс для круглой белой обводки вокруг аватаров

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#54]
![изображение](https://user-images.githubusercontent.com/9265326/122691993-38a25c00-d23b-11eb-895d-1016d9e02ac1.png)

Нам нужно добавлять руководителей программ и других людей на сайт - большие прямоугольные фото для этого не подходят. 

Нужен способ вставлять в белом круге фото.  Наш основной источник фото - mgimo.ru/people, но можем и у себя сохранять.

**Comment by epogrebnyak** [comment]
Размер круга - как в Assignees когда наводишь всплывает кружок - чуть больше чем ишью.

**Comment by necelentano** [comment]
Добавил стили для круглой рамки, размер фото 60px X 60px. Пример на этой [странице](https://epogrebnyak.github.io/finec-mgimo-v2/about/people/). К сожалению через markdown добавление стилей не поддерживается в Goldmark (только для заголовков).

**Comment by epogrebnyak** [comment]
Через HTML нормально, в далекой перспективе может быть свой shortcode сделаем, и может его предложим в тему doks - мне кажется он многим полезен.

**Comment by epogrebnyak** [comment]
@necelentano - небольшое дополнение - мы можем в класс добавить, чтобы при наведении мышки выскакивало маленькое окно с текстом из alt? что-то что по-моему называется `onMouseOver`. У нас сейчас alt используется для только для текста, если кратинка не найдена. 

Из изменение некритичное, если долго делать - то не надо.

**Comment by epogrebnyak** [comment]
Еще я для картинок, которые не сайта МГИМО сделал `static/images/person` директорию

**Comment by necelentano** [comment]
> @necelentano - небольшое дополнение - мы можем в класс добавить, чтобы при наведении мышки выскакивало маленькое окно с текстом из alt? что-то что по-моему называется `onMouseOver`. У нас сейчас alt используется для только для текста, если кратинка не найдена.
> 
> Из изменение некритичное, если долго делать - то не надо.

В принципе можно просто использовать html атрибут title. 
`<img src="https://mgimo.ru/upload/iblock/310/alborova.jpg" alt="Фамилия Имя Отчество" title="Любой текст здесь" class="rounded-photo">`
При наведении на фото будет всплывать tooltip с текстом, который укажем в title.

![html-title-attribute](https://user-images.githubusercontent.com/20335885/122913346-fc1d5000-d361-11eb-8791-af2e71d1af58.jpg)

Почитать по ссылке ниже.
[The alt Attribute Is NOT For Tooltips](https://robertnyman.com/2009/05/07/the-alt-attribute-is-not-for-tooltips/)

**Comment by necelentano** [comment]
Так как у нас уже есть в зависимостях Bootstrap по идее можно использовать их реализацию. Но там уже и разметка должна быть по их правилам, что возможно создаст трудности для тех, кто будет наполнять сайт содержанием.
[Bootstrap Tooltips](Tooltips)

**Comment by epogrebnyak** [comment]
@necelentano - спасибо - понял про `title`, отдельно менять на уровне Bootstrap не будем

**Comment by epogrebnyak** [comment]
Важный вопрос - мы можем внутри тега IMG задавать обтекание текстом с каким-то допуском и align - влево или вправо?

Мне нужно как-то погрузить картинки людей в текст - одну влево с обтеканием, другую вправо:

[здесь](https://epogrebnyak.github.io/finec-mgimo-v2/program/undergrad/fm/#%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%B5%D1%82%D0%B5%D0%BD%D1%86%D0%B8%D0%B8)

**Comment by necelentano** [comment]
Попробуйте к самой ссылке, внутри которой картинка, добавить специальные классы Bootstrap.
Пример.
```
<a href="https://mgimo.ru/people/kozlovskaya/" class="float-left mr-3 pt-2">
  <img
    src="https://mgimo.ru/upload/iblock/a9b/kozlovskaya.jpg"
    alt="Козловская Елена Александровна"
    class="rounded-photo"
  />
</a>
```
Почитать про эти классы [здесь](https://getbootstrap.com/docs/4.0/utilities/spacing/).
Результат такой.
![bootstrap-classes](https://user-images.githubusercontent.com/20335885/122921671-6a1a4500-d36b-11eb-966b-2cc1b70d245b.jpg)

**Comment by epogrebnyak** [comment]
Выглядит отлично, подскажите плс где почитать про `mr-10 pt-2`?

**Comment by necelentano** [comment]
По ссылке, которую я давал выше есть инфа об этом. В Bootstrap использую сокращения типа:
mr = margin-top
pt = padding top
Цифра в конце переменная $spacer с множителем = чем больше цифра тем больше внешний (или внутренний) отступ.
Ниже выделил основное.

```
Where property is one of:

m - for classes that set margin
p - for classes that set padding
Where sides is one of:

t - for classes that set margin-top or padding-top
b - for classes that set margin-bottom or padding-bottom
l - for classes that set margin-left or padding-left
r - for classes that set margin-right or padding-right
x - for classes that set both *-left and *-right
y - for classes that set both *-top and *-bottom
blank - for classes that set a margin or padding on all 4 sides of the element
Where size is one of:

0 - for classes that eliminate the margin or padding by setting it to 0
1 - (by default) for classes that set the margin or padding to $spacer * .25
2 - (by default) for classes that set the margin or padding to $spacer * .5
3 - (by default) for classes that set the margin or padding to $spacer
4 - (by default) for classes that set the margin or padding to $spacer * 1.5
5 - (by default) for classes that set the margin or padding to $spacer * 3
auto - for classes that set the margin to auto
(You can add more sizes by adding entries to the $spacers Sass map variable.)
```

**Comment by epogrebnyak** [comment]
Пример использования - тут: https://epogrebnyak.github.io/finec-mgimo-v2/program/undergrad/fm/#%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%B5%D1%82%D0%B5%D0%BD%D1%86%D0%B8%D0%B8
