### ISSUE TITLE
Оформить блог о выпускниках 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#55]
Сейчас лежит файл https://github.com/epogrebnyak/finec-mgimo-v2/blob/main/content/ru/blog/2021-uved-graduates
- просьба оформить его в заметку блога (перенести в папку видимо)

Еще у нас куча фото к блогу есть.

**Comment by necelentano** [comment]
Добавил блогпост с моковым заголовком. 
Нужно определить, что делать с полем lead в front matter? Это поле отображается в разметке списка блогпостов (думаю полезно), также он отображается в самом посте в самом начале с более крупным текстом. То есть нужно сам блогпост оформлять с учетом этого. В данном случае я удалил первый абзац из поста, чтобы не было дублирующего контента на станице. В случае отдельного блогпоста можно удалить lead из разметки в начале.

**Comment by epogrebnyak** [comment]
@necelentano, спасибо, я доправил
