### ISSUE TITLE
новый блок "Рассказывают студенты"

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#57]
@Ydvornikova1 - могли бы продулировать ссылку на докс документ с новыми выступлениями?

**Comment by epogrebnyak** [comment]
- https://drive.google.com/file/d/1HCKyiwd_ABTmVg97ZSnSnaxwdO05rIyC/view?usp=sharing 
- https://drive.google.com/file/d/1GYB-yq2bJuuPLkuEk7uWxG0sDL1LElYR/view?usp=sharing 
- https://drive.google.com/file/d/1BQLp-G873-HkEpMqT7qAtU3Btt-J0wjQ/view?usp=sharing

**Comment by Ydvornikova1** [comment]
Панасюк Милена Сергеевна Финансовая экономика и финансовые технологии 2024 https://drive.google.com/file/d/1HCKyiwd_ABTmVg97ZSnSnaxwdO05rIyC/view?usp=sharing  
Турищив Никита Владимирович Информационные технологии в международном бизнесе 2024 https://drive.google.com/file/d/1GYB-yq2bJuuPLkuEk7uWxG0sDL1LElYR/view?usp=sharing
Елизарова Яна Павловна Финансовый менеджмент 2024 https://drive.google.com/file/d/1BQLp-G873-HkEpMqT7qAtU3Btt-J0wjQ/view?usp=sharing

**Comment by Ydvornikova1** [comment]
Пока есть только один ролик на YouTube
Елизарова Яна Павловна Финансовый менеджмент 2024 https://youtu.be/MCysCFS3oK4
Позже обещали остальные

**Comment by Ydvornikova1** [comment]
Готовы ролики на YouTube
Панасюк Милена Сергеевна Финансовая экономика и финансовые технологии 2024 
https://www.youtube.com/watch?v=Gmh-N7BYbAs 
Турищив Никита Владимирович Информационные технологии в международном бизнесе 2024
https://www.youtube.com/watch?v=7Q9U55_MhgA

**Comment by naumov-v-m** [comment]
Задача ни на кого не заасайнена, можно брать в работу. Как понял нужно в раздел **Рассказывают студенты** https://finec.mgimo.ru/about/students/ добавить к имеющимся трем видео три видео с ютуба с транскрипцией видео?

**Comment by epogrebnyak** [comment]
@naumov-v-m - давайте какое-то одно видео одним коммитом, PR в ветку preview. #157 я закрою, там слишком много исправлений.

**Comment by naumov-v-m** [comment]
@epogrebnyak Взял первое видео https://youtu.be/MCysCFS3oK4, вставил его на страницу, добавил текстовое представление для видео:

```
Меня зовут Елизарова Яна. Я учусь
на факультете "Финансовой экономики", родом я из
города Самары.
<!-- История знакомства с МГИМО-->
На самом деле это все случилось довольно
спонтанно. Однажды вечером папа мне предложил поступить сюда, 
но тогда я немножко усомнилась своих силах и 
сказала: "Ну, нет - это точно не для меня." Но
позже, когда я сдала ЕГЭ, я
поняла, что у меня достаточно высокие
баллы для поступления, то подала документы
и сюда.
<!-- Что для тебя, как для студента, самое ценное в обучении? -->
Изучение различных языков, знакомство с
новыми преподавателями и перенятие их
опыта.
<!-- Будешь ли работать по специальности? И почему выбрали именно ее? -->
Я думаю, что если получится, то да - буду
работать. Мне нравится эта специальность,
потому что она включает себя и знание
экономики, знание управления и
естественные языки.
<!-- Назови три качества успешного студента -->
Наверное, это трудолюбие, открытость к
новым знаниям и любовь к обучению.
<!-- Три совета для будущего студента-->
Не боятся, быть открытым и искать больше
новых друзей.
```

Это видео отличается от видео уже представленных на странице - построено в виде диалога:

Вопросы идут в видео в виде вставок, в коде вопросы я выделил комментарием

**Comment by epogrebnyak** [comment]
> @epogrebnyak Взял первое видео https://youtu.be/MCysCFS3oK4, вставил его на страницу, добавил текстовое представление для видео:
> 
> ```
> Меня зовут Елизарова Яна. Я учусь
> на факультете "Финансовой экономики", родом я из
> города Самары.
> 
> На самом деле это все случилось довольно
> спонтанно. Однажды вечером папа мне предложил поступить сюда, 
> но тогда я немножко усомнилась своих силах и 
> сказала: "Ну, нет - это точно не для меня." Но
> позже, когда я сдала ЕГЭ, я
> поняла, что у меня достаточно высокие
> баллы для поступления, то подала документы
> и сюда.
> 
> Изучение различных языков, знакомство с
> новыми преподавателями и перенятие их
> опыта.
> 
> Я думаю, что если получится, то да - буду
> работать. Мне нравится эта специальность,
> потому что она включает себя и знание
> экономики, знание управления и
> естественные языки.
> 
> Наверное, это трудолюбие, открытость к
> новым знаниям и любовь к обучению.
> 
> Не боятся, быть открытым и искать больше
> новых друзей.
> ```
> 
> Это видео отличается от видео уже представленных на странице - построено в виде диалога:
> 
> Вопросы идут в видео в виде вставок, в коде вопросы я выделил комментарием

Немного смущают комментарии - можем их удалить? В ревью сложно понять из чего итоговый текст состоит.

**Comment by naumov-v-m** [comment]
Удалил комментарии, оставил такой текст:

```
Меня зовут Елизарова Яна. Я учусь на факультете "Финансовой 
экономики", родом я из города Самары.
Знакомство с МГИМО случилось довольно
спонтанно. Однажды вечером папа мне предложил поступить сюда, 
но тогда я немножко усомнилась своих силах и 
сказала: "Ну, нет - это точно не для меня." Но
позже, когда я сдала ЕГЭ, я поняла, что у меня достаточно высокие
баллы для поступления, то подала документы и сюда.
Для меня, как для студента, самое ценное в обучении - это
изучение различных языков, знакомство с новыми преподавателями и
перенятие их опыта.
Я думаю, что если получится, то буду работать по специальности. 
Я выбрала эту специальность, потому что она включает себя и 
знание экономики, знание управления и естественные языки.
По моему мнению тремя качествами успешного студента являются
трудолюбие, открытость к новым знаниям и любовь к обучению.
Мои три совета для будущего студента: не боятся, быть открытым 
и искать больше новых друзей.
```

**Comment by epogrebnyak** [comment]
Предлагаю здесь указать простым текстом: 

Меня зовут Елизарова Яна. Я учусь на факультете "Финансовой 
экономики", родом я из города Самары.
Знакомство с МГИМО случилось довольно
спонтанно. Однажды вечером папа мне предложил поступить сюда, 
но тогда я немножко усомнилась своих силах и 
сказала: "Ну, нет - это точно не для меня." Но
позже, когда я сдала ЕГЭ, я поняла, что у меня достаточно высокие
баллы для поступления, то подала документы и сюда.
Для меня, как для студента, самое ценное в обучении - это
изучение различных языков, знакомство с новыми преподавателями и
перенятие их опыта.
Я думаю, что если получится, то буду работать по специальности. 
Я выбрала эту специальность, потому что она включает себя и 
знание экономики, знание управления и естественные языки.
По моему мнению тремя качествами успешного студента являются
трудолюбие, открытость к новым знаниям и любовь к обучению.
Мои три совета для будущего студента: не боятся, быть открытым 
и искать больше новых друзей.

**Comment by epogrebnyak** [comment]
На всякий случай ссылка тут: https://finec.mgimo.ru/about/students/

**Comment by epogrebnyak** [comment]
Панасюк Милена Сергеевна Финансовая экономика и финансовые технологии 2024 https://drive.google.com/file/d/1HCKyiwd_ABTmVg97ZSnSnaxwdO05rIyC/view?usp=sharing
Турищив Никита Владимирович Информационные технологии в международном бизнесе 2024 https://drive.google.com/file/d/1GYB-yq2bJuuPLkuEk7uWxG0sDL1LElYR/view?usp=sharing

**Comment by epogrebnyak** [comment]
Closed via https://github.com/finec-mgimo/finec-mgimo.github.io/issues/178
