### ISSUE TITLE
перечислить курсы 1 года Henley (можно в ишью)

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#61]
![изображение](https://user-images.githubusercontent.com/9265326/122915696-b615bb80-d364-11eb-81bc-7c70846646d1.png)

https://www.icmacentre.ac.uk/study/undergraduate/bsc-finance-fintech#modules

Список:

- Introductory securites and markets (IC101)
- ...

(плохо копируется со страницы)

**Comment by veronmolosh** [comment]
- Introductory Securities and Markets (IC101)
- Introductory Finance/Trading Simulation I (IC102)
-  Introductory Economics for Business and Finance (IC103)
- Introductory Quantitative Techniques for Business and Finance (IC104)
- Ethics in Investment Management (BSc) (IC105)
- Business in Practice: Accounting for Managers (MM1F27)
