### ISSUE TITLE
Вставка картинов в публикации и посты

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#63]
![изображение](https://user-images.githubusercontent.com/9265326/123326765-4b21db80-d542-11eb-9ae4-5aaf6293c12c.png)

@necelentano - могли бы:

- [ ] сделать новый скриншот, сохранить в папке static/images
- [ ] вывести скриншот на странице программы - большой картинкой?

**Comment by epogrebnyak** [comment]
@necelentano  - посмотрите пожалуйста как лучше линковать большую  картинку 

Прототип - как сделано в getdoks - раздел с примерами сайтов, там брльшие скриншоты в публикации.

**Comment by epogrebnyak** [comment]
images во front matter - что нам дает?

**Comment by epogrebnyak** [comment]
видимо нам нужен шорткод img:

```
{{< img src="rectangle.png" alt="Rectangle" caption="<em>Rectangle</em>" class="border-0" >}}

```

https://getdoks.org/docs/recipes/images/

**Comment by epogrebnyak** [comment]
@necelentano - можете сделать скриншон сайта ai.mgimo.ru и вставить в страницу описания программы? У меня на экране сносит верстку.

**Comment by necelentano** [comment]
Добавил скриншот с программой "Искусственный интеллект".

**Comment by necelentano** [comment]
> видимо нам нужен шорткод img:
> 
> ```
> {{< img src="rectangle.png" alt="Rectangle" caption="<em>Rectangle</em>" class="border-0" >}}
> ```
> 
> https://getdoks.org/docs/recipes/images/

Вроде вы уже выяснили, что Shortcode'ы не работают в markdown, они для html. При генерации сайта происходит ошибка.

**Comment by epogrebnyak** [comment]
Шорткоды же нативный способ для Hugo и для doks - почему в маркдаун не
работают? Как раз там и работают.
Или я что-то не учитываю?.

вс, 27 июн. 2021 г., 17:35 Андрей | Andrey ***@***.***>:

**Comment by necelentano** [comment]
Хм, я попробовал у меня поломалось все. Может я что-то неправильно сделал.

**Comment by epogrebnyak** [comment]
Картинку в папку положили?

вс, 27 июн. 2021 г., 17:46 Андрей | Andrey ***@***.***>:

**Comment by necelentano** [comment]
картинку положил в content/ru/program/masters/ai-program.jpg
