### ISSUE TITLE
Перенос сайта на finec.mgimo.ru 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#67]
@necelentano, могли бы посмотреть как нам лучше перенести  на домен finec.mgimo.ru?

Это репо сделать finec-mgimo.github.io и скопировать сюда файл cname? 

Предыдущий сделать repo переименоввть в  old-website?

**Comment by necelentano** [comment]
Почитал немного по этой задаче.
Нужно в Settings - Pages - Custom domain добавить свой домен finec.mgimo.ru. Это создаст коммит с файлом CNAME в корне сайта. Хотя в документации Hugo советуют создать CNAME в папке static => [Use a Custom Domain](https://gohugo.io/hosting-and-deployment/hosting-on-github/#use-a-custom-domain)
Далее у своего домен провайдера нужно создать CNAME запись где нужно привязать finec.mgimo.ru к своему <аккаунт где размещен репозиторий сайта>.github.io (как я понял к своему аккаунту НЕ включая названия репозитория).
Возможно, у своего домен провайдера нужно будет указать IP адреса сервиса Github Pages:

- 185.199.108.153
- 185.199.109.153
- 185.199.110.153
- 185.199.111.153

Более детально можно почитать здесь => [Configuring a subdomain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain) и здесь => [Configuring an apex domain](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)

Также полезная ссылка => [Setup Hugo Site Generator on GitHub Pages with a Custom Domain - Connecting to GitHub Pages](https://gotask.net/tutorials/setup-hugo-on-github-pages-custom-domain/#connecting-to-github-pages)

**Comment by epogrebnyak** [comment]
У нас уже висит finec.mgimo.ru - там есть CNAME. 

@necelentano - просьба добавить/изменить в алгоритм переезда:


- [x] этот репо переносим в finec-mgimo

---

- [ ] переносим сюда CNAME 
- [ ] finec-mgimo.github.io переименовываем в finec-mgimo-v1.github.io
- [ ] этот репо переименуем в finec-mgimo.github.io 
- [ ] меняем внутренние ссылки рутовые (два-три блока ссылок в маркдауне)
- [ ] в этот момент сайт виден по адресу finec.mgimo.ru

Что может быть не так?

Дополнительно:
- составляем список, что есть на старом сайте

**Comment by necelentano** [comment]
Алгоритм переезда похож на правду.
Будут проблемы, будем искать решения.

**Comment by epogrebnyak** [comment]
Перенес сайт на https://finec.mgimo.ru/finec-mgimo-v2/

**Comment by necelentano** [comment]
С оформленным контентом сайт смотрится приятно.
А вы и хотели разместить сайт в поддиректории /finec-mgimo-v2/?
При переносе все получилось как и планировалось?

**Comment by necelentano** [comment]
Хедер сломан на этих страницах: 

1. https://finec.mgimo.ru/finec-mgimo-v2/program/masters/it-economics-and-data-management/ 
2. https://finec.mgimo.ru/finec-mgimo-v2/projects/machine-learning-mgimo-google/

Решение проблемы – названия файлов должны быть одинаковыми в обоих версиях (RU и EN).

На EN версии отсутствует ссылка Projects в верхнем меню.
