### ISSUE TITLE
видео о ФЭТ и Данилочкиной

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#69]

**Comment by Ydvornikova1** [comment]
Ролик Погребняк Е.В. Данилочкина Н.Г.
https://www.youtube.com/watch?v=5RYNMm6INLQ&t=1s

**Comment by Ydvornikova1** [comment]
Ролик Погребняк Е.В. Саркисян Ж.М.
https://www.youtube.com/watch?v=JKE4xgP18A8
