### ISSUE TITLE
можем ли добавать TOC

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#75]
Можем ли добавить TOC в публикации внутри разделов:

- "О нас" и "Проекты"?
- посты блогов?

**Comment by necelentano** [comment]
По идее можно, нужно будет переделать layout страниц и блогпостов.

**Comment by necelentano** [comment]
Добавил у себя локально правое меню с навигацией по странице в блогпосте. 
Выглядит как-то так.
![blog-on-this-page](https://user-images.githubusercontent.com/20335885/123549554-4c394f80-d772-11eb-8bc9-067fbcaca32d.jpg)

Коммитить изменения?
Таким же способом по идее можно изменить layout и для страниц "О нас" и "Проекты".
