### ISSUE TITLE
финализировать примеры записей в блоге

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#76]
- стилистика текста
- выбор фото
- подзаголовки
- результат (зачем писали)
- ссылки внутри блока (становится полезнее)

**Comment by epogrebnyak** [comment]
@levoro - могли бы посмотреть наши блоги по критериям выше? 

Например, добавить ссылку на фильм в блоге про кино?

**Comment by Levoro** [comment]
@epogrebnyak, документ создала у себя в аккаунте: https://github.com/Levoro/hat/blob/ethics_persisted/blog_movie.md. 

Нашла ссылку только на трейлер и добавила в этот абзац:

Николай Шувалов, 3 ФЭ: «Финансы в целом и деньги в частности — это очень интересная штука: о них знает каждый, но при этом четкого представления о них не имеет почти никто. Фильм „Откуда берутся деньги?“ отлично показывает каким образом работает гигантская финансовая машина».

Просмотр фильма нашла только по платной подписке:
https://www.idfa.nl/en/film/6c44e663-3562-445f-8d38-fa6ecefc2b66/oeconomia
https://vimeo.com/ondemand/oeconomia
https://dafilms.com/film/13064-oeconomia
 и т.д.

**Comment by epogrebnyak** [comment]
@Levoro - спасибо за ссылки. Я воспользовался ими, чтобы сделать редакцию заметки. 

По теме этого ищью - что считать хорошим постом:

- мы хотим 2-3 высококачественных фото или фото с хорошей композицией и сюжетом
- написано живым языком, без церемониала, 
- в заметке есть какая-то цель - документальные фильм это классно, дипломы крутые, колледжисты задают сложные вопросы, эта цель совпадает с намерением читателя и нам надо в это намерение попасть, это сложно
- мы даем полезные ссылки в блоге (где посмотреть дополнительную информацию по теме, что сделать если тема заинтересовала и т.д.)

**Comment by epogrebnyak** [comment]
По технике оформления:

 - картинки вставляем shortcode `figure`
 - пробуем шилды с программой и годом выпуска [![](https://img.shields.io/badge/ФМ-2024-blue)][management]
- можно использовать заголовки (но пока нет оглавления)
- в lead нельзя вставить маркдаун
- [не работает slug для адреса]()
