### ISSUE TITLE
блог о колледже 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#79]
https://odin.mgimo.ru/nov-pod-mgimo/4040-den-otkrytykh-dverej-fakulteta-finansovoj-ekonomiki-dlya-studentov-kolledzha-mgimo

Перенести блог (текст и картинки на этот сайт), зеркально скопировать в английскую версию (без перевода).

Имя папки и slug: finec-for-college-mgimo

**Comment by epogrebnyak** [comment]
@veronmolosh - посомтрите на https://finec.mgimo.ru/finec-mgimo-v2/blog/ - у вас блог отформатирован отлично от других

**Comment by epogrebnyak** [comment]
что-то не там с front matter

**Comment by necelentano** [comment]
все блогпосты в EN версии удалены, кроме finec-for-college-mgimo.

**Comment by epogrebnyak** [comment]
> все блогпосты в EN версии удалены, кроме finec-for-college-mgimo.

Не очень понял - зачем так - разъедется же форматирование. Я просил убрать меню, какая у нас логика удалять посты? Вы же их добавляли для форматирвоания

**Comment by necelentano** [comment]
я как раз об этом, их не стоило удалять. Просто заметил, что в EN версии нет постов.
