### ISSUE TITLE
изменения в английской версии

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#80]
Футер: ENGLISH VERSION Факультет финансовой экономики МГИМО

Заменить на 

MGIMO Financial Economics Faculty (Finec MGIMO)

Закомментировать в английской версии меню: О нас, Проекты, Блог, оставить контакты

**Comment by epogrebnyak** [comment]
@necelentano - верните блог на русском в английскую часть плс - форматирование едет без них.

**Comment by necelentano** [comment]
Вернул посты в EN версию.
Кстати, раз уж мы убрали навигацию по разделам (О нас, Проекты, Блог) в EN версии в верхнем меню, логично убрать ссылки на эти разделы в футере.

**Comment by epogrebnyak** [comment]
Я смотрел на футер, но мне жалко оттуда убирать )

**Comment by necelentano** [comment]
ОК, тогда пусть будут, с одной ссылкой футер действительно выглядит немного пустым.
