### ISSUE TITLE
фрагмент весеннего ДОД - выступление декана Е.В. Погребняка

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#81]
Вырезать выступление на ДОД для сайта FinecTV, оформить отдельным блогом

- [x] определить и согласовать временные метки начала и конца фрагмента (выступление Погребняка Е.В.)
- [x] вырезать фрагмент - внешний исполнитель
- [x] предоставить файл для размещения на youtube [FinecTV](https://www.youtube.com/channel/UCrDKAbWze5ai38Qr5w124Ww)

**Comment by epogrebnyak** [comment]
https://youtu.be/v6d0ke9QT9o?t=5909

**Comment by epogrebnyak** [comment]
https://www.youtube.com/watch?v=oUzcoYAwYyI

**Comment by epogrebnyak** [comment]
https://github.com/jdepoix/youtube-transcript-api/issues/124

**Comment by epogrebnyak** [comment]
Продублировать выступление на сайт https://www.youtube.com/watch?v=oUzcoYAwYyI

**Comment by TMichaelan** [comment]
В какой раздел добавить выступление?
