### ISSUE TITLE
daily comment

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#83]
Исправления:

- [x] неправильная фамилия в ИТМБ
- [x] неправильно указаны группы

Усовершенствовать:

- не на всех страницах есть Edit Page  (wontfix)
- прислать новый логотип МГИМО Одинцово
- разметсить два интервью (Хенли)
- победа Мельникова
- пересылка в соцсетях - откуда берется картинка (есть ли на ней размытость) - (wontfix)
- [x] slug в блоге

**Comment by necelentano** [comment]
> пересылка в соцсетях - откуда берется картинка

если не изменяет память картинка для соц. сетей указывается [здесь](https://github.com/finec-mgimo/finec-mgimo.github.io/blob/main/config/_default/params.toml#L4).

**Comment by epogrebnyak** [comment]
да, похоже ```images = ["finec-mgimo-footer.png"]```

**Comment by necelentano** [comment]
> slug в блоге

Вроде нужно добавить в config.toml. 
```
[permalinks]
  post = "/:slug/"
```
И, по идее, поле slug в front matter постов будет работать.

**Comment by epogrebnyak** [comment]
Эврика! Спасибо!

```
[permalinks]
  blog = "/blog/:slug/"
```

**Comment by epogrebnyak** [comment]
@veronmolosh - добавьте плс фото в УВЭД, выбрать лучшие несколько

**Comment by epogrebnyak** [comment]
- [ ] дэшборд успеваемости
- [ ] дэшборд абитуриентов

**Comment by epogrebnyak** [comment]
- [ ] дэшборд успеваемости
- [ ] дэшборд абитуриентов
- [ ] раздел "What next on the website?"
- [ ] телеграмм канал
- [ ] список компетенций финэка (после экзаменов)
- [ ] список выпускников и красных дипломов
