### ISSUE TITLE
списки членов ГИА

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#84]
@Ydvornikova1:

Может быть сделаем пост с короткими комметтариями членов и председателей ГИА? 

Понадобятся списки с должностями и фото.

Можно выборочно.

**Comment by Ydvornikova1** [comment]
Состав государственной экзаменационной комиссии по направлению подготовки 38.03.02 Менеджмент, профиль «Управление внешнеэкономической деятельностью»:

Председатель комиссии Степанов Виталий Андреевич,  кандидат экономических наук, заместитель генерального директора автономной некоммерческой организации «Московский экспортный центр»

Члены комиссии
Погребняк Евгений Владимирович, кандидат экономических наук, декан факультета финансовой экономики Одинцовского филиала МГИМО  МИД России;
Василюк Татьяна Николаевна, кандидат экономических наук, доцент, заведующий кафедрой  менеджмента  Одинцовского филиала МГИМО МИД России;
Сысоева Елена Васильевна, кандидат экономических наук, доцент кафедры    менеджмента  Одинцовского филиала МГИМО  МИД России;
Бондаренко Алексей Валерьевич, кандидат экономических наук, доцент кафедры менеджмента Одинцовского филиала МГИМО МИД России, генеральный директор общества с ограниченной ответственностью «Астема Групп»;
Тарусин Виктор Иванович, Президент Союза Одинцовская торгово-промышленная палата;
Салтыков Михаил Геннадьевич, начальник планового отдела ГК «DOOR HAN».

Состав государственной экзаменационной комиссии по направлению подготовки 38.03.01 Экономика, профиль «Информационные технологии в международном бизнесе»:

Председатель государственной экзаменационной комиссии: Вартанян Аревшад Апетович д-р эконом. наук, профессор кафедры информационных технологий в государственном управлении института инновационных технологий и государственного управления Федерального государственного бюджетного образовательного учреждения высшего образования Российского технологического университета (РТУ МИРЭА)

Члены государственной экзаменационной комиссии
Погребняк Евгений Владимирович канд. экон. наук, декан факультета финансовой экономики Одинцовского филиала ФГАОУ ВО МГИМО МИД России
Притчина Лариса Сергеевна канд. техн. наук, заведующий кафедрой математических методов и бизнес-информатики, заместитель директора Одинцовского филиала ФГАОУ ВО МГИМО МИД России
Пятов Алексей Александрович канд. экон. наук, старший консультант дирекции по управлению технологическими решениями ООО «САС Институт»;
 Лебедев Илья Олегович ведущий инженер – технический руководитель ООО «Мейл.ру».

**Comment by epogrebnyak** [comment]
Добавить состав ГИА в блог о защитах ИТМБ

**Comment by TMichaelan** [comment]
Отправил, добавил фотографии председателей.
