### ISSUE TITLE
поменять логотип мгимо на первой странице

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#86]
@necelentano  - у нас сейчас старый или новый логотип МГИМО на первой странице?

Нужен тот, который из мейла.

**Comment by epogrebnyak** [comment]
@necelentano - может быть что-то подчистить на https://finec.mgimo.ru/sandbox/logo/?

Нам по идее нуден там те же два логтипа, что и на первой, возможно в разных размерах, остальные не нужны.

**Comment by epogrebnyak** [comment]
Я предагаю этот убрать логотип, чтобы не путаться - у нас только те логотипы, которые из мейла болжны остаться по МГИМО

![изображение](https://user-images.githubusercontent.com/9265326/124010561-a262f880-d9e7-11eb-97f8-a54666d07ed8.png)

**Comment by necelentano** [comment]
Убрал логотип Кампус Одинцово.

**Comment by epogrebnyak** [comment]
Из static тоже надо убрать плс
