### ISSUE TITLE
[strategic]: больше картинок (picturise)

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#87]
Есть ощущение, что хорошо воспринимается сайт, где много картинок. Наше форматирование к этому не приспособлено, и картинок также не очень много. 

![изображение](https://user-images.githubusercontent.com/9265326/124010787-f2da5600-d9e7-11eb-8009-288a19fc1ed7.png)

**Comment by necelentano** [comment]
Да, картинки привлекают внимание когда хорошо сделать. Но, тогда придется всегда держать в уме что нужен какой-то imageCover для оформления поста, где даже может не быть картинок. Качество картинок тоже влияет на восприятие.

**Comment by epogrebnyak** [comment]
Superceded by #193
