### ISSUE TITLE
раздел About/"Партнерства"

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#88]
- Google 
- РБК
- SAS
- с кем заключены соглашения (из текста описания программ)

**Comment by TMichaelan** [comment]
Нужно добавить информации, отправлю пока сделаю draft: true

**Comment by epogrebnyak** [comment]
![image](https://user-images.githubusercontent.com/9265326/171353418-dc625b84-d1b5-408e-9109-1d6ed9fd8d6b.png)
