### ISSUE TITLE
вид первой и последующих страницы

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#9]
@necelentano 

> Реализовал поддержку двух языков + кнопка переключения языка. Создал страницу Контакты (без карты, пока как моковые данные), добавил указанный пост с картинками.

> Теперь нужно решить как делать главную страницу. Оставить сайдбар справа или убрать как было в вашем варианте.

**Comment by epogrebnyak** [comment]
Не ясно:

- у нас нет плана работ с соцсетями, их никто пока не ведет, не ясно про пиктограммы
- будем ли пробовать поставить логотип в верхнюю строку меню?
- кто-то как редактор может менять например раздел контакты - нужно кого-то обучить

Изменения - структура и оформление сайта (список будет дополняться):

Можно делать:

- [x] правый сайдбар предлагаю оставить
- [x] вместо слов Документация - Финэк МГИМО / Finec MGIMO
- [x] значок гитлаба надо поменять на гибтлаб и залинковать на текущий репо

Несрочно:

- [x] переключение на ночную версию здорово, но полумесяц не нравится в качестве значка, можно ли подобрать

Далее:

- [x] нужна минимальная структура разделов под наш сайт (отдельнео обсуждение, след)

Пока не делаем - оформление:

- [x] берем два новых логотипа (вынесу в отдельный ишью)
- [x] делаем пиктограммы для браузера (через генератор из логотипа)

Пока не делаем - контент:

- [x] ЕП: блог пост про то как развивался Causal Inference caйт, как пример 267dc6b 
- [x] классно голосовалки сделать, но не ясно как 267dc6b 
- [x] проанализировать результаты Google аналитики на текущем сайте  finec.mgimo.ru 267dc6b

**Comment by epogrebnyak** [comment]
- [x] заменить title на Финэк МГИМО / Finec MGIMO (или более длинную фразу, которая подходит для SEO - что-то про поступление)

**Comment by necelentano** [comment]
Обновил Title в конфиге. Количество символов (65) вроде в рамках дозволенного. _"Размер Title в Яндекс обычно находится в пределах — от 30 до 80 символов. Часто используемый размер Title в Google составляет 30-70 символов."_

**Comment by epogrebnyak** [comment]
Перекрывается #29 и #34
