### ISSUE TITLE
Нужен список выпускников

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#93]
Поздравляем выпускников факультета финансовой экономики: 

- Программа
- Дипломы с отличием
- Прочие выпускники

@Ydvornikova1 - могли бы взять список у коллег, сюда скопиоовать?

**Comment by Ydvornikova1** [comment]
38.04.01 ЭКОНОМИКА программа «Экономика фирмы и внешнеэкономическая деятельность»

Диплом с отличием: 

1.	Битарова Лариса Анатольевна 
2.	Жданович Константин Юрьевич
3.	Изотова Ольга Петровна
4.	Малютина Ирина Геннадиевна
5.	Соколов Никита Андреевич

Дипломы по направлению подготовки: 

1.	Гращенкова Анастасия Андреевна
2.	Геперидзе Ираклий Геннадович
3.	Евлоев Руслан Магомедович
4.	Королюк Андрей Леонидович
5.	Кудряшова Елена Андреевна
6.	Кумехов Георгий Константинович
7.	Лебедев Георгий Вячеславович
8.	Макаров Данил Андреевич
9.	Марченко Игорь Вячеславович
10.	Тарабановский Глеб Сергеевич
11.	Томашевский Артем Андреевич
12.	Фонарев Петр Михайлович

38.04.05 БИЗНЕС-ИНФОРМАТИКА  программа «Искусственный интеллект»

Диплом с отличием:

1.	Церех Юлия Константиновна
2.	Шамберг Николай Вячеславович

Дипломы по направлению подготовки:
 
1.	Бабаян Сергей Варданович
2.	Бужгеев Саян Николаевич
3.	Вострякова Виолетта Олеговна
4.	Глухов Иван Дмитриевич
5.	Григорьев Александр Олегович
6.	Калинин Виктор Александрович
7.	Кучеряев Александр Валерьевич
8.	Лобозов Петр Сергеевич
9.	Набиев Эльвин Шахлар оглы
10.	Пустовалова Анастасия Александровна
11.	Сиваков Евгений Глебович
12.	Шманенко Ульяна Ивановна

38.03.01 «ЭКОНОМИКА» программа «Информационные технологии в международном бизнесе»

Диплом с отличием:
 
1.	Денисова Анастасия Андреевна
2.	Куликову Анастасию Игоревну
3.	Медведеву Анастасию Михайловну
4.	Пузикова Алёна Валерьевна

Диплом  по направлению подготовки:
 
5.	Андронов Никита Александрович
6.	Виноградский  Александр Дмитриевич
7.	Горячева Екатерина Сергеевна
8.	Гурьев Владимир Русланович
9.	Гусев Павел Юрьевич
10.	Корнетов Богдан Рашидович
11.	Корытко Алексей Евгеньевич
12.	Павленко Виктор Сергеевич
13.	Письменский Валерий Александрович
14.	Хомец Дмитрий Витальевич
15.	Чагаева Анна Муратовна
16.	Чочишвили Георгий Тамазиевич

**Comment by Ydvornikova1** [comment]
38.04.01 ЭКОНОМИКА программа «Экономика фирмы и внешнеэкономическая деятельность»
Диплом с отличием: 
1.	Битарова Лариса Анатольевна 
2.	Жданович Константин Юрьевич
3.	Изотова Ольга Петровна
4.	Малютина Ирина Геннадиевна
5.	Соколов Никита Андреевич
Дипломы по направлению подготовки 
1.	Гращенкова Анастасия Андреевна
2.	Геперидзе Ираклий Геннадович
3.	Евлоев Руслан Магомедович
4.	Королюк Андрей Леонидович
5.	Кудряшова Елена Андреевна
6.	Кумехов Георгий Константинович
7.	Лебедев Георгий Вячеславович
8.	Макаров Данил Андреевич
9.	Марченко Игорь Вячеславович
10.	Тарабановский Глеб Сергеевич
11.	Томашевский Артем Андреевич
12.	Фонарев Петр Михайлович
38.04.05 БИЗНЕС-ИНФОРМАТИКА  программа «Искусственный интеллект»
Диплом с отличием:
1.	Церех Юлия Константиновна
2.	Шамберг Николай Вячеславович
Дипломы по направлению подготовки 
1.	Бабаян Сергей Варданович
2.	Бужгеев Саян Николаевич
3.	Вострякова Виолетта Олеговна
4.	Глухов Иван Дмитриевич
5.	Григорьев Александр Олегович
6.	Калинин Виктор Александрович
7.	Кучеряев Александр Валерьевич
8.	Лобозов Петр Сергеевич
9.	Набиев Эльвин Шахлар оглы
10.	Пустовалова Анастасия Александровна
11.	Сиваков Евгений Глебович
12.	Шманенко Ульяна Ивановна

38.03.01 «ЭКОНОМИКА» программа «Информационные технологии в международном бизнесе»
Диплом с отличием 
1.	Денисова Анастасия Андреевна
2.	Куликову Анастасию Игоревну
3.	Медведеву Анастасию Михайловну
4.	Пузикова Алёна Валерьевна
Диплом  по направлению подготовки 
5.	Андронов Никита Александрович
6.	Виноградский  Александр Дмитриевич
7.	Горячева Екатерина Сергеевна
8.	Гурьев Владимир Русланович
9.	Гусев Павел Юрьевич
10.	Корнетов Богдан Рашидович
11.	Корытко Алексей Евгеньевич
12.	Павленко Виктор Сергеевич
13.	Письменский Валерий Александрович
14.	Хомец Дмитрий Витальевич
15.	Чагаева Анна Муратовна
16.	Чочишвили Георгий Тамазиевич
38.03.02 «Менеджмент» программа «Управление внешнеэкономической деятельностью»
Диплом с отличием 
1.	Имамназарова Диана Фуркатовна
2.	Котельников Петр Михайлович
3.	Прядеин Даниил Игоревич
Диплом  по направлению подготовки
1.	Бадалян Инесса Артуровна
2.	Барабошин Алексей Игоревич
3.	Барто Филипп Георгиевич
4.	Берсанов Юсуп Анатольевич
5.	Воробьев Александр Дмитриевич
6.	Воробьев Владислав Сергеевич
7.	Гончарова Ольга Алексеевна
8.	Егизекова Алина Аскаровна
9.	Закарян Давид Арменович
10.	Иконникова Виола Викторовна
11.	Ковальчук Богдан Юрьевич
12.	Ковальчук Максим Юрьевич
13.	Куруцова Аминат Мухтаровна
14.	Мамедова Ульвия Руфатовна
15.	Рзаев Нофтоли Равилевич
16.	Серебряков Никита Евгеньевич
17.	Соснюк Кирилл Геннадьевич
18.	Шульженко Анастасия Павловна
