### ISSUE TITLE
 review langauge switch works as intended

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#95]
If we have a page in Russian language, that does not have a correspnding page in English , our current switch breaks the layout: the github icon is misplaced as below.

https://finec.mgimo.ru/alumni/

![изображение](https://user-images.githubusercontent.com/9265326/125613814-07b03af7-8f41-4f14-857e-a5b57a66d1b5.png)

Also ther is no 'EN' on this page. If there is corresponding english page - the link should probably link to root `/`.

**Comment by epogrebnyak** [comment]
@AdnanBhatti - can you look? not this is not a critical issue, an enhancement. if you have an alternative - please make it on a new branch

@necelentano made the original switch implementation, he can review the enhancements

**Comment by epogrebnyak** [comment]
I think here is where we have the switch: https://github.com/finec-mgimo/finec-mgimo.github.io/blob/801f3a3d7ea605f6edb0a3a707fc9a0a71a2800f/layouts/partials/header/header.html

**Comment by necelentano** [comment]
Глянул со свежей головой, и вроде нашел ошибку. Больше не должно быть проблем со сломанным хедером. 
p.s. Ошибка была банальна, не там закрыл тег ul :(

**Comment by necelentano** [comment]
По идее, теперь можно удалить все в EN директории без последствий, просто пропадет ссылка на другой язык.

**Comment by necelentano** [comment]
Для сохранения минимальной структуры в EN версии, вероятно не стоит удалять весь контент (я про программы, которые есть в меню навигации слева). Разделы Блог, О нас и Проекты, по идее, можно спокойно удалить из EN версии.

**Comment by epogrebnyak** [comment]
Нам было бы большим подспорьем не дублировать материалы, сильно бы
облегчило жизнь.

Обратите внимание - модет быть ситуация, когда что-то в блоге на
английском, без зеркальной статьи на русском.

У нас на англицском получается только первая страница, контакты и блог,
видимо.

Не очень понятно, что делать боковиком, где по программам - их переводить
не хочется



чт, 15 июл. 2021 г., 10:34 Андрей | Andrey ***@***.***>:

**Comment by necelentano** [comment]
Как я понял, боковик слева на главной будет пустым, нужно хотя бы подзаголовки оставить UNDERGRADUATE, GRADUATE. Вполне возможно, что ничего не сломается даже если из левого сайдбара удалить все.

**Comment by epogrebnyak** [comment]
Кстати да - заголовки пусть останутся, они не мешают, а доков внутри не
будет

чт, 15 июл. 2021 г., 15:08 Андрей | Andrey ***@***.***>:

**Comment by epogrebnyak** [comment]
О, @necelentano, у нас кто-то форкит нашу разарботку, это чудесно! )

Вопрос: может экспериментально удалить в английском описание какой-то программы?

**Comment by necelentano** [comment]
Помню, когда мы "бились" над нужным отображением программ, у меня были ошибки из-за которых все программы и даже подзаголовки программ (UNDERGRADUATE, GRADUATE) не отображались вообще. При этом верстка страницы не ломалась – левый сайдбар был просто пустым. Думаю в EN версии можно просто удалить все программы и, по идее, все будет нормально работать.

**Comment by epogrebnyak** [comment]
@super16 - могли бы про верить, насколько оправданно у нас свитч на английский сделан - если ok - закрыть ишью, если нет - написать что можем поменять, заранее спасибо

**Comment by super16** [comment]
LGTM
