### ISSUE TITLE
Security policy and search 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#96]
Note comments here: https://github.com/h-enk/doks/discussions/320#discussioncomment-1002454

To answer before fixing:
- [ ] what is content security issue?
- [ ] what is search issue - does it work?

**Comment by epogrebnyak** [comment]
@AdnanBhatti - here the question is to detect what is wroong first, before wefix it

**Comment by AdnanBhatti** [comment]
ok we'll detect the issue

**Comment by necelentano** [comment]
About Saerch issue.
[Here](https://getdoks.org/docs/reference-guides/flexsearch/) we call new FlexSearch(). But in var index we don't have any indexed data. Maybe is this a problem?

**Comment by epogrebnyak** [comment]
I was not using the search and honestly maubevit never worked, so
thecquesrjon is rather how do we set up search from scratch, from the
beginning.

чт, 15 июл. 2021 г., 13:09 Андрей | Andrey ***@***.***>:
