### ISSUE TITLE
font change in English version 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#97]
Something makes the website change font in the English version:

![изображение](https://user-images.githubusercontent.com/9265326/126879680-d8f35434-aa05-4678-a246-13d3e75d3ae8.png)

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/126879691-80f27216-09ce-4c8b-9504-f15b1bfdc359.png)

**Comment by necelentano** [comment]
Странно, в обеих версиях указаны такие шрифты:
```
font-family: "Jost",-apple-system,blinkmacsystemfont,"Segoe UI",roboto,"Helvetica Neue",arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
```
Видимо у EN шрифтов letter-spacing меньше по умолчанию, поэтому английская версия выглядит "сжато" с меньшим промежутком между букв. По факту шрифт одинаковый.

Сам шрифт Jost можно посмотреть на [Google Fonts](https://fonts.google.com/?query=jost) – выбрать Latin или Cyrillic.
