### ISSUE TITLE
разместить новое интервью 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#98]
https://mgimo.ru/about/news/departments/pogrebnyak-ffe-2021/

**Comment by epogrebnyak** [comment]
Добрый день, я представляю факультет финансовой экономики МГИМО. Это уникальный факультет, на котором собраны компетенции в области менеджмента, экономики, бизнес-информатики и анализа данных. Мы находимся сейчас рядом с деканатом, рядом с приемной комиссией, где уже сейчас приходят абитуриенты, которые поступают на наши бакалаврские и магистерские программы. Как они выбирают между тремя бакалаврскими и тремя магистерскими программами? Если я хочу заниматься собственным бизнесом, управлять проектами, участвовать в работе стартапов, если для меня предпринимательство и управление проектами – важная составляющая часть карьеры, я пойду, скорее всего, на программу «Финансовый менеджмент». Если меня интересует карьера в крупных банках, страховых компаниях, финансовом секторе, интересует экономическая аналитика и изменение в финансовом секторе, финансовых технологиях, секторе финтех, я пойду на программу по направлению «Экономика», которая называется «Финансовая экономика и финансовые технологии». Эта программа близко интегрирована с профильной программой Henley Business School, что сильно повышает академическое качество этой программы. Наконец, если я вижу себя в IT-секторе со стороны бизнеса, я готов поучаствовать во внедрении IT-технологий в крупных компаниях, я пойду на программу «Информационные технологии в международном бизнесе» (ИТМБ) и буду заниматься внедрением IT-технологий, разработкой IT-продуктов и анализом данных благодаря фундаментальной подготовке в области математики и эконометрики, а также анализа данных.
Хочу сказать, что эти программы очень доступны. Мы боремся с таким имиджем, когда даже текущие студенты говорят о том, что они не верили в то, что можно поступить в МГИМО, просто сдав ЕГЭ. Это действительно так: у нас нет дополнительных вступительных испытаний, у нас есть набор ЕГЭ по программам, и, проходя минимальный балл и ранжированный отбор, вы поступаете на наш факультет. Мы ждем абитуриентов из разных школ, из разных регионов и готовы предложить вам захватывающий путь в области экономики, менеджмента, финансов и бизнес-информатики. 
Я бы хотел сказать два слова о важнейших партнерствах, которые развивает наш факультет. В первую очередь наше партнерство с компанией Google. Вместе с Google мы сейчас разрабатываем курс, который называется «Управление проектами анализа данных и машинного обучения». Несмотря на сложное, громкое название, этот проект, этот курс ориентирован на нетехнических специалистов – на, можно сказать, гуманитариев, для которых часто вход в профессию анализа данных затруднен. Благодаря компании Google мы даем возможность ребятам почувствовать себя на стороне заказчика проекта анализа данных и посмотреть, что действительно определяет успех такого проекта: логика выбора задач, ход принятия решений, итерации проектов; что делать в случае, если данных нет; какие методы анализа выбрать и как представить результаты. Это очень ценные навыки, которые позволяют специалистам из разных предметных областей, в том числе гуманитарных, влиться в сферу анализа данных. Мы очень рады предложить этот курс нашим студентам и студентам других факультетов МГИМО. 
Узнать о факультетах МГИМО, в том числе о нашем, можно двумя, но в нашем случае тремя способами. Это официальный сайт МГИМО, это сайт кампуса, в нашем случае Одинцовского кампуса МГИМО, на котором базируется наш факультет, а также собственный сайт факультета, который показывает его профиль, его специфику и дает какие-то дополнительные возможности. Дополнительная возможность на нашем сайте finec.mgimo.ru – это кнопка «Ознакомительный визит». Мы с большим интересом и очень оперативно отвечаем на вопросы, которые приходят через сайт. В свою очередь, будущие студенты, абитуриенты, их родители хвалят эту кнопку и нас за то, что информация приходит очень оперативно. Сайт является самостоятельной разработкой факультета, он сделан на платформе GitHub – там же, где хостятся крупнейшие программные опенсорсные проекты. Мне кажется, это первый вузовский, первый факультетский сайт, размещенный на GitHub. Если вам интересно, как сделан этот сайт, заходите на finec.mgimo.ru, нажимайте кнопку «GitHub», и вы увидите источник нашего сайта и даже сможете поучаствовать в его разработке.

**Comment by epogrebnyak** [comment]
Разбить текст на разделы, добавить вверху видео (через тэг), ставить как блог с той же датой, что и на главном сайте

**Comment by TMichaelan** [comment]
Нужна ссылка на видео и я бы добавил имя фамилию и титул человека который представляет факультет, чтобы "Добрый день, я представляю факультет финансовой экономики МГИМО." это предложение имело смысл.

**Comment by TMichaelan** [comment]
Отправил на модерацию

**Comment by epogrebnyak** [comment]
> Отправил на модерацию

@TMichaelan - лучше с ссылкой писать, чтобы посомотерть можно было быстро

**Comment by TMichaelan** [comment]
@epogrebnyak - переделал, 
http://localhost:1313/blog/finec-mgimo-interview/ 

https://finec.mgimo.ru/blog/finec-mgimo-interview/
