### ISSUE TITLE
Google analytics does not collect data from website 

### ISSUE THREAD

**Issue by epogrebnyak** [necelentano/finec-mgimo-v2#99]
<script defer data-domain="finec.mgimo.ru" src="https://plausible.io/js/plausible.js"></script>

**Comment by epogrebnyak** [comment]
Нам нужно добавить снипет на все страницы сайта, куда-то в базовый шаблон. 

Может быть отдельный файл со сниппетом, и далее в темплейт добавляется

**Comment by necelentano** [comment]
Добавил скрипт Plausible Analytics в partials/analytics.html и подключил его к базовому шаблону baseof.html. Теперь этот скрипт есть на всех страницах сайта.

**Comment by epogrebnyak** [comment]
@super16 - мы отходим от идеи с Plaisible - нам надо где-то в конфигах иметь возможность вставить ид счетчиков Yandex и Google и собирать аналитику

**Comment by super16** [comment]
Добавил [PR](https://github.com/finec-mgimo/finec-mgimo.github.io/pull/145), где убрал интеграцию Plausible, а также добавил внедрение Яндекс.Метрики и Google Analytics (в Hugo из коробки идёт).

В `config/_default/config.toml` есть соответствующие поля `params/yandexMetrika` и `googleAnalytics`, при заполнении которых включаются соответствующие сервисы. Если поля пустые, то код интеграции не включается на страницу.

К сожалению, у меня нет возможности проверить работоспособность, поэтому перед вливанием бы протестил локально с тестовыми значениями

**Comment by epogrebnyak** [comment]
Смерджил, тоже токенов нет, буду постепенно добавлять, о работе напишу в ишью, спасибо за РR

**Comment by epogrebnyak** [comment]
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(89232698, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/89232698" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

**Comment by epogrebnyak** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FT4YJWWBMK"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FT4YJWWBMK');
</script>

**Comment by epogrebnyak** [comment]
Чтобы начать сбор данных, добавьте на сайт тег с помощью идентификатора потока данных:G-FT4YJWWBMK

**Comment by epogrebnyak** [comment]
Yandex получаю аналитику, но не вижу статистики просмотров дальше первой страницы

GA что-то не показывает данные пока

**Comment by epogrebnyak** [comment]
GA не показывает аналитику

**Comment by super16** [comment]
@epogrebnyak есть гипотеза, что проблема с GA может быть в том, что GA настроен на запросы с http, а не https ([гайд как исправить в интерфейсе GA](https://www.monsterinsights.com/docs/change-the-protocol-of-your-website-from-http-to-https-in-google-analytics/))

**Comment by super16** [comment]
С метрикой, наверное, стоит [проиндексировать сайт](https://yandex.ru/support/metrica/general/link-webmaster.html)

**Comment by epogrebnyak** [comment]
> @epogrebnyak есть гипотеза, что проблема с GA может быть в том, что GA настроен на запросы с http, а не https ([гайд как исправить в интерфейсе GA](https://www.monsterinsights.com/docs/change-the-protocol-of-your-website-from-http-to-https-in-google-analytics/))

@super16:  похоже дело не в https - выглядит, что у нас настройка на него как раз

![изображение](https://user-images.githubusercontent.com/9265326/177220624-f4935cf8-67ac-4a54-835d-7abec10c8061.png)

У нас такой код для тегов?

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FT4YJWWBMK"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-FT4YJWWBMK');
</script>
```

**Comment by super16** [comment]
Нет, я не учёл, что в проекте используется не последняя версия hugo, и там не был обновлён встроенный тег для GA. Заменил на актуальный код в [PR #190](https://github.com/finec-mgimo/finec-mgimo.github.io/pull/190)

**Comment by epogrebnyak** [comment]
> Нет, я не учёл, что в проекте используется не последняя версия hugo, и там не был обновлён встроенный тег для GA. Заменил на актуальный код в [PR #190](https://github.com/finec-mgimo/finec-mgimo.github.io/pull/190)

@super16  - счетчик заработал, спасибо!
